"""The file-size rule (scripts/validate_size.py, owner 2026-10-07: «чтобы файлы не содержали больше тысячи строк на один файл»,
«допустимо, если будет 1050 или 1100, это окей»): about 1000 lines and 160 characters, failing above 1100 and 200; the files over
today are held in design/baseline.json "file_size" and may only shrink. Small files written here, never the repositories' own."""
import importlib.util, json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location("hyvalidate", ROOT / "scripts/validate.py")
V = importlib.util.module_from_spec(spec); spec.loader.exec_module(V)
FS = V.FS
C = json.loads((ROOT / "design/contract.json").read_text(encoding="utf-8"))


def write(tmp_path, name, lines=1, width=10, extra=""):
    p = tmp_path / name; p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text("".join("x" * width + "\n" for _ in range(lines)) + extra, encoding="utf-8")
    return p


def found(paths, base=None):
    return [(Path(i["file"]).name, i["line"]) for i in FS.check([str(p) for p in paths], {"files": base or {}})]


def test_a_new_file_over_the_ceiling_fails_and_near_the_target_only_warns(tmp_path):
    big = write(tmp_path, "big.py", 1101)
    near = write(tmp_path, "near.js", 1050)
    wide = write(tmp_path, "wide.css", 3, extra="y" * 201 + "\n")
    ok = write(tmp_path, "ok.html", 1000, extra="z" * 200 + "\n" + "w" * 180 + "\n")
    assert found([big, near, wide, ok]) == [("big.py", 1101), ("wide.css", 4)]
    msg = FS.check([str(big)], {})[0]["msg"]
    assert "1101 lines" in msg and "1100" in msg and "split it by responsibility" in msg
    FS.check([str(near)], {})
    assert "near.js (1050)" in FS.summary()


def test_a_baselined_file_that_stays_the_same_or_shrinks_passes(tmp_path):
    p = write(tmp_path, "canvas.html", 1500, extra="a" * 300 + "\n" + "b" * 250 + "\n")
    key = str(p)
    base = {key: {"lines": 1502, "long_lines": 2, "max_line": 300}}
    assert found([p], base) == []
    write(tmp_path, "canvas.html", 1200, extra="a" * 300 + "\n")
    assert found([p], base) == []
    assert "1 shrank" in FS.summary()


def test_a_baselined_file_that_grows_fails(tmp_path):
    p = write(tmp_path, "server.py", 1500, extra="a" * 300 + "\n")
    base = {str(p): {"lines": 1501, "long_lines": 1, "max_line": 300}}
    write(tmp_path, "server.py", 1501, extra="a" * 300 + "\n")                      # one line more
    got = FS.check([str(p)], {"files": base})
    assert [(i["line"], "1502 lines" in i["msg"] and "holds it at 1501" in i["msg"]) for i in got] == [(1502, True)]
    write(tmp_path, "server.py", 1400, extra="a" * 300 + "\n" + "b" * 201 + "\n")   # shorter, one more long line
    assert found([p], base) == [("server.py", 1401)]
    write(tmp_path, "server.py", 1400, extra="a" * 400 + "\n")                      # the long line got longer
    got = FS.check([str(p)], {"files": base})
    assert len(got) == 1 and "400 characters" in got[0]["msg"] and got[0]["line"] == 1401


def test_data_generated_vendored_lang_tables_and_urls_are_not_counted(tmp_path):
    for name in ("vendor/three.js", "node_modules/a/index.js", "dist/app.js", "build/x.py", "_review/b.js", ".cache/c.js",
                 "lib.min.js", "data.json", "notes.md", "icon.svg"):
        write(tmp_path, name, 1200, width=300)
    write(tmp_path, "gen.js", 1200, width=300, extra="").write_text("// @generated by a script\n" + "x\n" * 1200)
    write(tmp_path, "ui/lang-board.js", 10, width=400)
    write(tmp_path, "lang.js", 10, width=400)
    url = "https://example.com/" + "p" * 300
    write(tmp_path, "links.py", 3, extra=f'SRC = "{url}"  # the source\n<a href="{url}">x</a>\n')
    assert FS.check([str(tmp_path)], {}) == []
    write(tmp_path, "lang.js", 1101)                                                  # a lang table still has the line ceiling
    assert found([tmp_path]) == [("lang.js", 1101)]


def test_through_validate_a_size_item_is_always_new_and_never_written_to_the_static_baseline(tmp_path, monkeypatch):
    monkeypatch.setattr(V, "BASELINE", tmp_path / "baseline.json")
    p = write(tmp_path, "x.css", 1101, width=4)
    items, files = V.run([str(p)], C)
    assert [i["rule"] for i in items] == ["file-size"]
    V.write_baseline(items)
    assert json.loads((tmp_path / "baseline.json").read_text())["static"]["counts"] == {}
    new, _, _ = V.compare(*V.run([str(p)], C))
    assert [i["rule"] for i in new] == ["file-size"]


def test_update_seeds_once_then_only_lowers(tmp_path):
    b = tmp_path / "baseline.json"; b.write_text(json.dumps({"static": {"counts": {}}}))
    a = write(tmp_path, "a.py", 1300, extra="q" * 250 + "\n")
    c = write(tmp_path, "c.py", 10)
    FS.update(b, [str(tmp_path)])
    sec = json.loads(b.read_text())
    assert sec["static"] == {"counts": {}} and sec["file_size"]["files"] == {str(a): {"lines": 1301, "long_lines": 1, "max_line": 250}}
    write(tmp_path, "a.py", 1350, extra="q" * 260 + "\n")                            # grew: the baseline does not follow
    write(tmp_path, "c.py", 1200)                                                     # a new big file is not added
    FS.update(b, [str(tmp_path)])
    assert json.loads(b.read_text())["file_size"]["files"] == {str(a): {"lines": 1301, "long_lines": 1, "max_line": 250}}
    write(tmp_path, "a.py", 1050)                                                     # back under the limits: dropped
    FS.update(b, [str(tmp_path)])
    assert json.loads(b.read_text())["file_size"]["files"] == {}
    assert c.exists()
