// The Russian words of Home (review/home.html); the English text in the code is the key (ui/i18n.js says how).
// en: only plurals and context keys ("ctx::Text").
hyLang({
  en: {
    "{n} frames": ["{n} frame", "{n} frames"],
    "+{n} images": ["+{n} image", "+{n} images"],
    "−{n} images": ["−{n} image", "−{n} images"],
    "{n} groups": ["{n} group", "{n} groups"],
    "{n} notes": ["{n} note", "{n} notes"],
    "{n} headings": ["{n} heading", "{n} headings"],
    "{n} moves": ["{n} move", "{n} moves"],
    "{n} annotations": ["{n} annotation", "{n} annotations"],
    "{n} drawings": ["{n} drawing", "{n} drawings"],
    "{n} other changes": ["{n} other change", "{n} other changes"],
    "{n} more pages": ["{n} more page", "{n} more pages"],
  },
  ru: {
    // the page's markup
    "Hyimg · Home": "Hyimg · Главная",
    "Sections": "Разделы",
    "Recent": "Недавние",
    "All boards": "Все доски",
    "Find a board": "Найти доску",
    "New board": "Новая доска",
    "Project icon": "Иконка проекта",
    "Home: the board will finish loading on its own": "Главная: доска догрузится сама",
    "The project on Home: the board will finish loading on its own": "Проект на главной: доска догрузится сама",
    "Loading": "Загрузка",
    // the boards' cards and rows
    // the card's line is data only (owner 2026-10-08: «Зачем мне эта писанина? ... frames достаточно»): «16 мин назад · 7 814 кадров · 3,5 ГБ»
    "Never opened": "еще не открывалась",
    "yesterday": "вчера",
    "{n} frames": ["{n} кадр", "{n} кадра", "{n} кадров"],
    "Open {name}": "Открыть {name}",
    "Remove from favorites": "Убрать из избранного",
    "Add to favorites": "В избранное",
    "state::Open": "открыта",
    "Folder unavailable": "Папка недоступна",
    "folder unavailable": "папка недоступна",
    "Locate folder…": "Указать папку…",
    "Board actions": "Действия с доской",
    "Open the folder in Finder · {path}": "Открыть папку в Finder · {path}",
    "View": "Вид",
    "Cards": "Карточки",
    "List": "Список",
    "Name": "Название",
    "Project": "Проект",
    "Path": "Путь",
    "Edited": "Изменена",
    // news on a board without the owner (owner 2026-10-06): the red number's tooltip and the filter
    "{n} new": ["{n} новое", "{n} новых", "{n} новых"],
    "+{n} images": ["+{n} картинка", "+{n} картинки", "+{n} картинок"],
    "−{n} images": ["−{n} картинка", "−{n} картинки", "−{n} картинок"],
    "{n} groups": ["{n} группа", "{n} группы", "{n} групп"],
    "{n} notes": ["{n} заметка", "{n} заметки", "{n} заметок"],
    "{n} headings": ["{n} заголовок", "{n} заголовка", "{n} заголовков"],
    "{n} moves": ["{n} перемещение", "{n} перемещения", "{n} перемещений"],
    "{n} annotations": ["{n} аннотация", "{n} аннотации", "{n} аннотаций"],
    "{n} drawings": ["{n} рисунок", "{n} рисунка", "{n} рисунков"],
    "{n} other changes": ["{n} другое изменение", "{n} других изменения", "{n} других изменений"],
    // the page first, its name as written (2026-10-08: «+2 картинки на Страница 1» is not Russian); the tooltip's head ends in «·»
    "{what} on {page}": "{page}: {what}",
    "{n} new: {list}": ["{n} новое · {list}", "{n} новых · {list}", "{n} новых · {list}"],
    "{n} more pages": ["еще {n} страница", "еще {n} страницы", "еще {n} страниц"],
    "Page 1": "Страница 1",
    "AI": "ИИ",
    "Filter": "Фильтр",
    "Only new": "Только с новым",
    "Only the boards where something changed without you": "Только доски, где без вас что-то менялось",
    "Nothing new on the boards": "На досках ничего нового",
    // the bell on Home: every board's news (ui/homebell.js)
    "Notifications": "Уведомления",
    "{n} more": "еще {n}",
    // the sidebar and the heads
    "Project name": "Имя проекта",
    "No project": "Без проекта",
    "Favorites": "Избранное",
    "Projects": "Проекты",
    "New project": "Новый проект",
    "No boards yet": "Досок пока нет",
    "A board is a <b>Finder folder</b> with images": "Доска это <b>папка Finder</b> с картинками",
    "Nothing found for “{q}”.": "Ничего не нашлось по «{q}».",
    "Every board is in a project.": "Все доски лежат в проектах.",
    "No boards in this project yet": "В проекте пока нет досок",
    "<b>Drag boards here</b> or pick a project in a board's menu": "<b>Перетащи доски сюда</b> или выбери проект в меню доски",
    // the menus
    "Open": "Открыть",
    "Rename…": "Переименовать…",
    "Move to “{name}”": "В проект «{name}»",
    "Move to a new project": "В новый проект",
    "Remove from “{name}”": "Убрать из проекта «{name}»",
    "Locate the folder in Finder…": "Указать папку в Finder…",
    "Open folder": "Открыть папку",
    "Show in Finder": "Показать в Finder",
    "Stop server": "Остановить сервер",
    "Remove board…": "Убрать доску…",
    "Start server": "Запустить сервер",
    // a board's server key on its card while the app starts or stops it (ui/homeserver.js)
    "Starting the server": "Запускаю сервер",
    "Stopping the server": "Останавливаю сервер",
    "Rename project": "Переименовать проект",
    "Project icon…": "Иконка проекта…",
    "Delete project": "Удалить проект",
    "boards stay": "доски останутся",
    "Board from a Finder folder…": "Доска из папки Finder…",
    // a hyimg:// link the app could not open (native/LinkRouting.swift, owner 2026-10-07)
    "The board of this link is not in Hyimg on this Mac": "Доски из этой ссылки нет в Hyimg на этом Mac",
    "This link can't be opened in Hyimg": "Эту ссылку Hyimg открыть не может",
  },
});
