// The Russian words of the primitives' showcase (ui/hy/showcase.js) and of the primitives themselves; the English text in the code is the
// key (ui/i18n.js says how). en: only plurals and context keys ("ctx::Text").
hyLang({
  en: {
    "{n} live": ["{n} live", "{n} live"],
  },
  ru: {
    // the primitives (ui/hy)
    "More information": "Подробнее",
    // the showcase: titles
    "Hyimg UI · primitives": "Hyimg UI · примитивы",
    "{n} live": ["{n} живой", "{n} живых", "{n} живых"],
    "Buttons": "Кнопки",
    "Choices": "Выбор",
    "Marks and text": "Метки и текст",
    "Dark · Round": "Темная · Круглые",
    "Dark · Pro": "Темная · Pro",
    "Light · Round": "Светлая · Круглые",
    "Light · Pro": "Светлая · Pro",
    "variants": "варианты",
    "sizes": "размеры",
    "states": "состояния",
    "options": "варианты выбора",
    "Last event": "Последнее событие",
    "The primitives did not load: restart the server (View › Restart Server)": "Примитивы не загрузились: перезапустите сервер (Вид › Перезапустить сервер)",
    // the showcase: words on the controls
    "Duplicate": "Дублировать",
    "Save": "Сохранить",
    "Cancel": "Отмена",
    "Delete": "Удалить",
    "Reset": "Сбросить",
    "Button": "Кнопка",
    "Grid": "Сетка",
    "Copy": "Копировать",
    "Arrange": "Упорядочить",
    "Off": "Выкл",
    "Dark": "Темная",
    "Light": "Светлая",
    "Auto": "Авто",
    "Activity": "События",
    "Versions": "Версии",
    "Cards": "Карточки",
    "List": "Список",
    "Rows": "Ряды",
    "Snap to grid": "Привязка к сетке",
    "Show hidden layers": "Скрытые слои",
    "Some layers": "Часть слоев",
    "Locked": "Заблокировано",
    "Take": "Взять",
    "Idea": "Идея",
    "No": "Нет",
    "Video": "Видео",
    "Pinned": "Закреплен",
    "Notes": "Заметки",
    "new": "новых",
    "A footnote, <b>key words</b> in ink": "Сноска, <b>главное</b> цветом текста",
    "Opens the frame in Image Studio": "Открывает фрейм в Image Studio",
    "The group's long title stays in one line and ends in an ellipsis": "Длинный заголовок группы остается в одной строке и обрезается многоточием",
    "Settings": "Настройки",
    "History": "История",
    "Close": "Закрыть",
    "Yellow": "Желтый",
    "No colour": "Без цвета",
    // the showcase: the Hints family (the key hint's words are ui/lang-common.js «hint::»)
    "Hints": "Подсказки",
    "Key hint · beside what you are doing": "Подсказка клавиш · рядом с тем, что вы делаете",
    "used 3 times: quieter, 5 times: gone": "3 раза: бледнее, 5 раз: пропадает",
    "Hint bar · a Studio or a tool just opened": "Строка подсказок · только что открытая студия или инструмент",
    "Tip · for someone who is only looking": "Совет · для того, кто только смотрит",
    "closed with ×: the bulb brings them back": "закрыт ×: лампочка вернет советы",
    // the showcase: round 15's micro UI (owner 2026-10-09)
    "Micro UI": "Микро-элементы",
    "1 · mini toggle": "1 · мини-переключатель",
    "All nodes": "Все узлы",
    "2 · the count is the switch": "2 · число и есть переключатель",
    "3 · micro segments": "3 · микросегменты",
    "Space": "Пространство",
    "Local": "Локальное",
    "World": "Мировое",
    "Units": "Единицы",
    "Shading": "Затенение",
    "Material": "Материал",
    "Solid view": "Сплошной вид",
    "Render": "Рендер",
    "4 · status, 6 px, no glow": "4 · статус, 6 px, без свечения",
    "The current camera": "Текущая камера",
    "Working": "Идет работа",
    "5 · drag the letter, ⇧ ×10, ⌥ ×0.1, a click types": "5 · тяни букву, ⇧ ×10, ⌥ ×0,1, щелчок вводит число",
    "Opacity": "Прозрачность",
    "6 · tiny stepper": "6 · маленький степпер",
    "Columns": "Колонки",
    "Padding": "Отступ",
    "7 · change dot, colour dot": "7 · точка изменения, точка цвета",
    "Changed": "Изменено",
    "8 · icons on hover, a set one stays": "8 · значки при наведении, включенный остается",
    "Shadow": "Тень",
    "Lock": "Заблокировать",
  },
});
