// The Russian words of Home (review/home.html); the English text in the code is the key (ui/i18n.js says how).
// en: only plurals and context keys ("ctx::Text").
hyLang({
  en: {
    "{n} frames on the canvas": ["{n} frame on the canvas", "{n} frames on the canvas"],
    "+{n} images": ["+{n} image", "+{n} images"],
    "−{n} images": ["−{n} image", "−{n} images"],
    "{n} groups": ["{n} group", "{n} groups"],
    "{n} notes": ["{n} note", "{n} notes"],
    "{n} headings": ["{n} heading", "{n} headings"],
    "{n} moves": ["{n} move", "{n} moves"],
    "{n} other changes": ["{n} other change", "{n} other changes"],
    "{n} more pages": ["{n} more page", "{n} more pages"],
  },
  ru: {
    // the page's markup
    "Hyimg · Home": "Hyimg · Главная",
    "Sections": "Разделы",
    "Recent": "Недавние",
    "All boards": "Все доски",
    "Find a board": "Найти доску",
    "New board": "Новая доска",
    "Project icon": "Иконка проекта",
    "Home: the board will finish loading on its own": "Главная: доска догрузится сама",
    "The project on Home: the board will finish loading on its own": "Проект на главной: доска догрузится сама",
    "Loading": "Загрузка",
    // the settings (the language's own names, English and Русский, are never translated)
    "App settings": "Настройки приложения",
    "Language": "Язык",
    "Theme": "Тема",
    "Like macOS: light by day, dark in the evening, if the system is set that way": "Как в macOS: днем светлая, вечером темная, если так настроено в системе",
    "Auto": "Авто",
    "Dark theme, graphite paper": "Темная тема, графитовая бумага",
    "Dark": "Темная",
    "Light theme, light paper": "Светлая тема, светлая бумага",
    "Light": "Светлая",
    "Paper grain": "Зерно бумаги",
    "Very fine": "Очень тонкое",
    "Fine": "Тонкое",
    "Visible": "Заметное",
    "Strong": "Сильное",
    "Engine": "Движок",
    "The macOS engine, like Safari: draws on the CPU": "Движок macOS, как Safari: рисует процессором",
    "Chrome's engine inside Hyimg: the GPU draws the board and it stays smooth": "Движок Chrome внутри Hyimg: доска рисуется видеокартой и не тормозит",
    "Rendering": "Отрисовка",
    "Each image as its own element": "Каждая картинка отдельным элементом",
    "Standard": "Обычная",
    "From afar the images are drawn as one canvas (canvas 2D)": "Издалека картинки рисуются одним холстом (canvas 2D)",
    "Canvas": "Холст",
    "From afar the GPU draws the images (WebGL), like Figma": "Издалека картинки рисует видеокарта (WebGL), как в Figma",
    "Notes": "Заметки",
    "Translucent, with a strong blur under them": "Полупрозрачные, под ними сильное размытие",
    "Glass": "Стекло",
    "Solid, no blur": "Плотные, без размытия",
    "Solid": "Плотные",
    "Dots": "Точки",
    "A grid of CSS layers, as always": "Сетка из слоев CSS, как всегда",
    "Classic": "Обычные",
    "One WebGL layer: alive, waves run through them when you drop images": "Одним слоем WebGL: живые, по ним идут волны, когда кладешь картинки",
    "Shadows": "Тени",
    "Panels and buttons float above the board": "Плашки и кнопки парят над доской",
    "With shadows": "С тенями",
    "Panels lie flat": "Плашки лежат плоско",
    "No shadows": "Без теней",
    "Corners": "Углы",
    "Round buttons and panels": "Кнопки и плашки круглые",
    "Round": "Круглые",
    "Stricter: almost square, with a moderate radius": "Строже: почти квадратные, с умеренным радиусом",
    "Paper color": "Цвет бумаги",
    "Paper color in the dark theme": "Цвет бумаги в темной теме",
    "Paper color in the light theme": "Цвет бумаги в светлой теме",
    "Restore the default colors": "Вернуть цвета по умолчанию",
    "Reset": "Сбросить",
    "Dots visibility": "Видимость точек",
    "Dots visibility, percent": "Видимость точек, процентов",
    "For <b>the whole app</b>: Home and every board": "Для <b>всего приложения</b>: главная и все доски",
    // the boards' cards and rows
    "Never opened": "еще не открывалась",
    "Edited just now": "изменена только что",
    "Edited {n} min ago": "изменена {n} мин назад",
    "Edited {n} h ago": "изменена {n} ч назад",
    "Edited yesterday": "изменена вчера",
    "Edited {date}": "изменена {date}",
    "{n} frames on the canvas": ["{n} кадр на холсте", "{n} кадра на холсте", "{n} кадров на холсте"],
    "Open {name}": "Открыть {name}",
    "Remove from favorites": "Убрать из избранного",
    "Add to favorites": "В избранное",
    "state::Open": "открыта",
    "Folder unavailable": "Папка недоступна",
    "folder unavailable": "папка недоступна",
    "Locate folder…": "Указать папку…",
    "Board actions": "Действия с доской",
    "Open the folder in Finder · {path}": "Открыть папку в Finder · {path}",
    "View": "Вид",
    "Cards": "Карточки",
    "List": "Список",
    "Name": "Название",
    "Project": "Проект",
    "Path": "Путь",
    "Edited": "Изменена",
    // news on a board without the owner (owner 2026-10-06): the red number's tooltip and the filter
    "{n} new": ["{n} новое", "{n} новых", "{n} новых"],
    "+{n} images": ["+{n} картинка", "+{n} картинки", "+{n} картинок"],
    "−{n} images": ["−{n} картинка", "−{n} картинки", "−{n} картинок"],
    "{n} groups": ["{n} группа", "{n} группы", "{n} групп"],
    "{n} notes": ["{n} заметка", "{n} заметки", "{n} заметок"],
    "{n} headings": ["{n} заголовок", "{n} заголовка", "{n} заголовков"],
    "{n} moves": ["{n} перемещение", "{n} перемещения", "{n} перемещений"],
    "{n} other changes": ["{n} другое изменение", "{n} других изменения", "{n} других изменений"],
    "{what} on {page}": "{what} на {page}",
    "{n} more pages": ["еще {n} страница", "еще {n} страницы", "еще {n} страниц"],
    "Page 1": "Страница 1",
    "AI": "ИИ",
    "Filter": "Фильтр",
    "Only new": "Только с новым",
    "Only the boards where something changed without you": "Только доски, где без вас что-то менялось",
    "Nothing new on the boards": "На досках ничего нового",
    // the sidebar and the heads
    "Project name": "Имя проекта",
    "No project": "Без проекта",
    "Favorites": "Избранное",
    "Projects": "Проекты",
    "New project": "Новый проект",
    "No boards yet": "Досок пока нет",
    "A board is a <b>Finder folder</b> with images": "Доска это <b>папка Finder</b> с картинками",
    "Nothing found for “{q}”.": "Ничего не нашлось по «{q}».",
    "Every board is in a project.": "Все доски лежат в проектах.",
    "No boards in this project yet": "В проекте пока нет досок",
    "<b>Drag boards here</b> or pick a project in a board's menu": "<b>Перетащи доски сюда</b> или выбери проект в меню доски",
    // the menus
    "Open": "Открыть",
    "Rename…": "Переименовать…",
    "Move to “{name}”": "В проект «{name}»",
    "Move to a new project": "В новый проект",
    "Remove from “{name}”": "Убрать из проекта «{name}»",
    "Locate the folder in Finder…": "Указать папку в Finder…",
    "Open folder": "Открыть папку",
    "Show in Finder": "Показать в Finder",
    "Stop server": "Остановить сервер",
    "Hide interface · ⌘.": "Скрыть интерфейс · ⌘.", "Zoom": "Приближение", "Slide": "Сдвиг",
    "Everything around the board grows a little and fades out": "Все вокруг доски чуть увеличивается и растворяется",
    "Everything slides off to its edge and fades": "Все уезжает к своему краю и растворяется",
    "Remove board…": "Убрать доску…",
    "Start server": "Запустить сервер",
    "Rename project": "Переименовать проект",
    "Project icon…": "Иконка проекта…",
    "Delete project": "Удалить проект",
    "boards stay": "доски останутся",
    "Board from a Finder folder…": "Доска из папки Finder…",
  },
});
