// The Russian words of the shared modules of review/ui (menu, toasts, projicon, video, layout-sync, keyhints); the English text in the code is the key (ui/i18n.js says how).
// en: only plurals and context keys ("ctx::Text").
hyLang({
  en: {
    "{n} files": ["{n} file", "{n} files"],
    "{n} images are in several places on the board": ["{n} image is in several places on the board", "{n} images are in several places on the board"],
  },
  ru: {
    // menu.js: «Показать в Finder» for library files
    "Opened 5 folders, {n} more not opened": "Открыты 5 папок, еще {n} не открыты",
    "This file is outside the library": "Этот файл вне библиотеки",
    "The file is not there, or the server was not restarted": "Файла нет на месте или сервер не перезапущен",
    "Finder did not open": "Finder не открылся",
    // menu.js: «Open in <App>» on a card's menu (owner 2026-10-06)
    "Open in default app": "Открыть в программе по умолчанию",
    "Open in {app}": "Открыть в {app}",
    "The file did not open": "Файл не открылся",
    // menu.js: the marking colours (a folder in the library's tree, a node in the 3D editor's tree)
    "Colour": "Цвет",
    "No colour": "Без цвета",
    "yellow": "желтый", "orange": "оранжевый", "red": "красный", "pink": "розовый", "purple": "фиолетовый", "blue": "синий", "green": "зеленый", "grey": "серый",
    // toasts.js
    "Close": "Закрыть",
    "Close notification": "Закрыть уведомление",
    // projicon.js: a project's icon picker
    "Icon": "Иконка",
    "Emoji": "Эмодзи",
    "Text color": "Цвет текста",
    "Custom": "Свой",
    "paste or ⌃⌘Space": "вставь или ⌃⌘Пробел",
    // video.js
    "This engine does not play H.264, ffmpeg is needed": "Этот движок не проигрывает H.264, нужен ffmpeg",
    "This video did not load": "Это видео не загрузилось",
    "This video does not play: ffmpeg could not read it": "Это видео не играет: ffmpeg не смог его прочитать",
    "This video does not play in this browser: its format or codec": "Это видео не играет в этом браузере: формат или кодек",
    // layout-sync.js: folders like the board
    "{n} files": ["{n} файл", "{n} файла", "{n} файлов"],
    "Folders on disk follow the board: every board edit arranges the files again. Click for the menu, where you can turn it off": "Папки на диске повторяют доску: каждая правка доски раскладывает файлы заново. Клик: меню, там можно выключить",
    "Like the board": "Как на доске",
    "Folders like the board": "Папки как на доске",
    "Folders arranged like the board: {files}": "Папки разложены как на доске: {files}",
    "Couldn't arrange the folders: ": "Не получилось разложить по папкам: ",
    "run::Couldn't arrange the folders: ": "Не удалось разложить по папкам: ",
    "Arrange folders like the board…": "Разложить по папкам как на доске…",
    "Always keep folders like the board": "Всегда держать папки как на доске",
    "Undo the last layout": "Отменить последнюю раскладку",
    "Folders will follow the board: after every board edit the files arrange themselves": "Папки будут повторять доску: после каждой правки доски файлы разложатся сами",
    "Folders no longer follow the board": "Папки больше не следуют за доской",
    "Couldn't switch the mode: ": "Не удалось переключить режим: ",
    "Layout undone: {files} back in place": "Раскладка отменена: {files} на прежних местах",
    ", {n} not found": ", не нашлось {n}",
    ". “Like the board” mode is off": ". Режим «как на доске» выключен",
    "Couldn't undo the layout: ": "Не удалось отменить раскладку: ",
    "Arrange folders like the board": "Разложить по папкам как на доске",
    "Looking at the board and folders…": "Смотрю доску и папки…",
    "Couldn't work out the layout: ": "Не удалось посчитать раскладку: ",
    "before": "было",
    "after": "стало",
    "“{name}”": "«{name}»",
    "The image files will move on disk into folders by the board's pages, groups and notes{pages}. New folders will appear, and old ones left without a single file will be deleted. The board, frames and old links will keep opening the images. You can undo it in this same menu.": "Файлы картинок переедут на диске в папки по страницам, группам и заметкам доски{pages}. Появятся новые папки, а старые, в которых не останется ни одного файла, будут удалены. Доска, фреймы и старые ссылки продолжат открывать картинки. Отменить можно в этом же меню.",
    " (pages {list})": " (страницы {list})",
    "will move": "переедут",
    "new folders": "новых папок",
    "empty folders deleted": "пустых папок удалим",
    "stay in place": "останутся на месте",
    "For example": "Например",
    "Every image on the board is already in its folder.": "Все картинки с доски уже лежат в своих папках.",
    "Their json files move with the images ({files}).": "Вместе с картинками едут их json ({files}).",
    "Matching names for {files}: the folder each came from is added to the name.": "Совпали имена у {files}: к имени добавится папка, откуда файл пришел.",
    "{n} images are in several places on the board": ["{n} картинка лежит в нескольких местах доски", "{n} картинки лежат в нескольких местах доски", "{n} картинок лежат в нескольких местах доски"],
    "it will go": "она ляжет",
    "they will go": "они лягут",
    "into the folder “{name}” at the project root": "в папку «{name}» в корне проекта",
    "into the project root": "в корень проекта",
    "Files not on any board ({n}) are left alone.": "Файлы, которых нет на досках ({n}), не трогаем.",
    "On: every board edit arranges the files again. Off: only now, once": "Включено: каждая правка доски раскладывает файлы заново. Выключено: только сейчас, один раз",
    "Cancel": "Отмена",
    "folders::Arrange": "Разложить",   // the folders laid out like the board; the selection bar's «Arrange» is «Упорядочить» (lang-board.js)
    "Arranging…": "Раскладываю…",
    "Arranged: {files}": "Разложено: {files}",
    ", new folders: {n}": ", новых папок {n}",
    ", empty ones deleted: {n}": ", удалено пустых {n}",
    ". Folders will follow the board": ". Папки будут повторять доску",
    "Everything is already like the board. Folders will follow the board": "Все уже лежит как на доске. Папки будут повторять доску",
    "Everything is already like the board": "Все уже лежит как на доске",
    // storage.js: Settings › Storage (2026-10-07)
    "{n} GB": "{n} ГБ", "{n} MB": "{n} МБ", "{n} KB": "{n} КБ",
    "Storage": "Хранилище",
    "Measuring…": "Считаю…",
    "Measuring the folders…": "Считаю папки…",
    "Not measured yet": "Еще не посчитано",
    "Boards": "Доски",
    "Made by Hyimg": "Создано Hyimg",
    "Thumbnails, previews and stills in the boards' folders: Hyimg draws them again": "Миниатюры, превью и кадры в папках досок: Hyimg нарисует их заново",
    "Cache": "Кэш",
    "Clear {size}": "Очистить {size}",
    "Nothing to clear": "Нечего очищать",
    "App copies · {n}": "Копии приложения · {n}",
    "To the Trash": "В корзину",
    "Duplicates": "Повторы",
    "Identical files in a board's folder: the space the extra copies take": "Одинаковые файлы в папке доски: сколько места занимают лишние копии",
    "Memory now": "Память сейчас",
    "Graphics": "Графика", "Pages": "Страницы", "Servers": "Серверы", "Window": "Окно", "Services": "Службы", "Scan": "Подсчет", "Other": "Другое", "Blender": "Blender",
    "Server memory": "Память сервера",
    "«Clear» removes <b>only Hyimg's own cache</b>, never your files": "«Очистить» удаляет <b>только кэш Hyimg</b>, ваши файлы не трогает",
    "Clear the cache, {size}?": "Очистить кэш, {size}?",
    "Video copies, 3D conversions and folders of removed boards. Hyimg makes them again when needed": "Копии видео, переводы 3D и папки удаленных досок. Hyimg сделает их заново, когда понадобятся",
    "Clear": "Очистить",
    "Move {n} old app copies to the Trash?": "Старые копии приложения в корзину: {n}?",
    "The 2 newest stay. They can be put back from the Trash": "2 новые останутся. Из корзины их можно вернуть",
    "Nothing was deleted: {why}": "Ничего не удалено: {why}",
    "Freed {size}": "Освобождено {size}",
    "{n} copies in the Trash, {size} freed": "Копий в корзине: {n}, освобождено {size}",
    "Sort by size": "Сортировать по размеру",
    "Size": "Размер",
    "Lost processes · {n}": "Потерянные процессы · {n}",
    "Hyimg servers, Blender and their helpers left running by a test or an agent that ended": "Серверы Hyimg, Blender и их помощники, которые оставил закончившийся тест или агент",
    "Stop": "Остановить",
    "Stop {name}?": "Остановить {name}?",
    "It frees {size}. The app's own servers are not touched": "Освободится {size}. Серверы самого приложения не трогаем",
    "Not stopped: {why}": "Не остановлено: {why}",
    "Stopped, {size} freed": "Остановлено, освобождено {size}",
    "Server {port}": "Сервер {port}",
    "Server": "Сервер",
    "{n} h": "{n} ч",
    "{n} min": "{n} мин",
    "Thumbnails per board": "Миниатюры на доску",
    "Thumbnails in all": "Миниатюры всего",
  },
});
