// The Russian words of the board (review/canvas.html); the English text in the code is the key (ui/i18n.js says how).
// en: only plurals and context keys ("ctx::Text").
hyLang({
  en: {
    "{n} pages": ["{n} page", "{n} pages"],
    "{n} empty files stay in the library: there is nothing to place": ["{n} empty file stays in the library: there is nothing to place", "{n} empty files stay in the library: there is nothing to place"],
    "Split into {n} pages?": ["Split into {n} page?", "Split into {n} pages?"],
    "library::{n} frames": ["{n} frame", "{n} frames"],
    "{n} frames": ["{n} frame", "{n} frames"],
    "{n} notes": ["{n} note", "{n} notes"],
    "{n} groups": ["{n} group", "{n} groups"],
    "{n} frames of this version are no longer on disk": ["{n} frame of this version is no longer on disk", "{n} frames of this version are no longer on disk"],
    "{n} autosaves": ["{n} autosave", "{n} autosaves"],
    "Added {n} frames": ["Added {n} frame", "Added {n} frames"],
    "Removed {n} frames": ["Removed {n} frame", "Removed {n} frames"],
    "{n} frames · double-click the name to rename": ["{n} frame · double-click the name to rename", "{n} frames · double-click the name to rename"],
    "{n} frames went to the archive": ["{n} frame went to the archive", "{n} frames went to the archive"],
    "{n} folders, ": ["{n} folder, ", "{n} folders, "],
    "Moved to “{page}”: {n} objects": ["Moved to “{page}”: {n} object", "Moved to “{page}”: {n} objects"],
    "Pasted {what} on {n} objects": ["Pasted {what} on {n} object", "Pasted {what} on {n} objects"],
  },
  ru: {
    "Crop: drag the frame ·": "Кроп: тяни рамку ·",
    "note color (for all selected), remembered for new ones": "цвет стикера (для всех выделенных), запоминается для новых",
    "click": "клик",
    "zoom": "масштаб",
    "in a note": "в стикере",
    "Visible": "Заметное",
    "with sound, and pause (Space: for one selected video)": "со звуком и пауза (пробел: у одного выделенного видео)",
    "Shortcuts": "Клавиши",
    "Home": "Главная",
    "Light theme, light paper": "Светлая тема, светлая бумага",
    "a frame from the library onto the canvas": "кадр из библиотеки на холст",
    "♥ Like · F": "♥ Нравится · F",
    "Very fine": "Очень тонкое",
    "bold, italic;": "жирный, курсив;",
    "▶ in the video's corner,": "▶ в углу видео,",
    "Home: all boards · ⌘⇧H": "Главная: все доски · ⌘⇧H",
    "ungroup": "расформировать группу",
    "Collection": "Коллекция",
    "Library": "Библиотека",
    "Close": "Закрыть",
    "Like": "Нравится",
    "Dots": "Точки",
    "sticky note: under the pointer, type right away": "стикер-заметка: под курсором, текст сразу",
    "Undo · ⌘Z": "Отменить · ⌘Z",
    "Frame library": "Библиотека кадров",
    "Search by name and prompt": "Поиск по имени и промпту",
    "Paper grain": "Зерно бумаги",
    "Strong": "Сильное",
    "Round buttons and panels": "Кнопки и плашки круглые",
    "Classic": "Обычные",
    "With shadows": "С тенями",
    "No shadows": "Без теней",
    "Standard": "Обычная",
    "the note's yellow dot": "желтый кружок стикера",
    "Sticky note": "Стикер-заметка",
    "+ scroll wheel, pinch": "+ колесо, щипок",
    "Save the current state as a separate version · Enter": "Сохранить текущее состояние отдельной версией · Enter",
    "Corners": "Углы",
    "turn the ratio ·": "повернуть пропорцию ·",
    "size (a group from every side, a heading and a frame by a corner)": "размер (у группы со всех сторон, у заголовка и кадра за угол)",
    "Video": "Видео",
    "arrange the selection as a block": "упорядочить выделенное блоком",
    "group": "сгруппировать",
    "show all": "показать все",
    "Redo": "Вернуть",
    "double-click on empty space": "двойной клик по пустому",
    "Solid": "Плотные",
    ", the note button": ", кнопка со стикером",
    "Show all": "Показать все",
    "The current state is saved as a separate version first, nothing is lost": "Текущее состояние сначала сохранится отдельной версией, ничего не пропадет",
    "pages": "страницы",
    "A grid of CSS layers, as always": "Сетка из слоев CSS, как всегда",
    "+ mouse": "+ мышь",
    "Notifications": "Уведомления",
    "Restore the default colors": "Вернуть цвета по умолчанию",
    "move frames": "перенести кадры",
    "corner or edge": "угол или сторона",
    "Close · Esc": "Закрыть · Esc",
    "Chrome's engine inside Hyimg: the GPU draws the board and it stays smooth": "Движок Chrome внутри Hyimg: доска рисуется видеокартой и не тормозит",
    "belongs to the whole group": "относится ко всей группе",
    "plays muted; pointer away: the still again": "играет без звука, ушла: снова картинка",
    "Translucent, with a strong blur under them": "Полупрозрачные, под ними сильное размытие",
    "Glass": "Стекло",
    "Rendering": "Отрисовка",
    "type size, five steps (for all selected notes)": "размер шрифта, пять ступеней (для всех выделенных стикеров)",
    "drag it to a frame or group: an arrow (to remove: click the arrow,": "потяни к кадру или группе: стрелка (убрать: клик по стрелке,",
    "Version history": "История версий",
    "Space": "Пробел",
    "scroll wheel, trackpad": "колесо, трекпад",
    ", double-click in crop": ", двойной клик в кропе",
    "One WebGL layer: alive, waves run through them when you drop images": "Одним слоем WebGL: живые, по ним идут волны, когда кладешь картинки",
    "drag": "перетащить",
    "the whole frame": "весь кадр",
    "a copy of the frame for a second crop": "копия кадра для второго кропа",
    "the first button of the bar, double-click to rename": "первая кнопка панели, двойной клик переименовать",
    "Show all · ⇧1": "Показать все · ⇧1",
    "Versions": "Версии",
    "+ drag": "+ перетащить",
    "Project on Home": "Проект на главной",
    "All collections": "Все коллекции",
    "Show or hide the library · \\": "Показать или скрыть библиотеку · \\",
    "Like macOS: light by day, dark in the evening, if the system is set that way": "Как в macOS: днем светлая, вечером темная, если так настроено в системе",
    "Paper color": "Цвет бумаги",
    "Canvas settings": "Настройки холста",
    "Engine": "Движок",
    "“Area” above a note": "«Область» над стикером",
    "Restore this version": "Восстановить эту версию",
    "a dashed zone: every frame inside is linked, the edges stretch": "пунктирная зона: все кадры внутри привязаны, края тянутся",
    "Actions": "Действия",
    "a note over frames": "стикер поверх кадров",
    "Round": "Круглые",
    "Pages": "Страницы",
    "Dots visibility, percent": "Видимость точек, процентов",
    "remove from the canvas to the archive": "убрать с холста в архив",
    "marquee,": "рамка,",
    "Sticky note · N": "Стикер-заметка · N",
    "Paper color in the light theme": "Цвет бумаги в светлой теме",
    "apply, cancel the crop": "применить, отменить кроп",
    "Back to current": "Вернуться к текущей",
    "a note inside a group, linked to nothing": "стикер внутри группы, ни к чему не привязан",
    "colored dots above a note": "цветные кружки над стикером",
    "The macOS engine, like Safari: draws on the CPU": "Движок macOS, как Safari: рисует процессором",
    "at the start of a line: a list,": "в начале строки: список,",
    "Dots visibility": "Видимость точек",
    "Timeline": "Таймлайн",
    "apply ·": "применить ·",
    "Fine": "Тонкое",
    "From afar the GPU draws the images (WebGL), like Figma": "Издалека картинки рисует видеокарта (WebGL), как в Figma",
    "Version name": "Название версии",
    "Notifications: what agents put on the boards": "Уведомления: что агенты положили на доски",
    "the line at the bottom of a video": "линия внизу видео",
    "Hide frames rated “No”": "Скрыть кадры с оценкой «Нет»",
    "Canvas": "Холст",
    "Activity": "События",
    "Name the current version…": "Назвать текущую версию…",
    "Panels lie flat": "Плашки лежат плоско",
    "Reset": "Сбросить",
    "Light": "Светлая",
    "Open the frame to view and rate it": "Открыть кадр для просмотра и оценки",
    "Theme": "Тема",
    "cancel ·": "отмена ·",
    "Close history": "Закрыть историю",
    "move the canvas": "двигать холст",
    "Stricter: almost square, with a moderate radius": "Строже: почти квадратные, с умеренным радиусом",
    "Page 1": "Страница 1",
    "select several": "выделить несколько",
    "tidy: rows stay, gaps even": "причесать: строки остаются, промежутки ровные",
    "drag: seek": "потяни: перемотка",
    "while typing": "при вводе текста",
    "a copy": "копия",
    "crop; a video: crop and trim": "кроп; у видео кроп и обрезка",
    "double-click": "двойной клик",
    "an image: the Image mode; a video: crop and trim": "картинка: режим «Картинка»; видео: кроп и обрезка",
    "⤢ in a video's pill": "⤢ на плашке видео",
    "full screen,": "во весь экран,",
    "leaves it": "выход",
    "Open": "Открыть",
    "apply": "применить",
    "Dark theme, graphite paper": "Темная тема, графитовая бумага",
    "Solid, no blur": "Плотные, без размытия",
    "a heading in large type": "заголовок крупным шрифтом",
    "Drag frames from the library on the left": "Перетащи кадры из библиотеки слева",
    "From afar the images are drawn as one canvas (canvas 2D)": "Издалека картинки рисуются одним холстом (canvas 2D)",
    "Auto": "Авто",
    "For <b>the whole app</b>: Home and every board": "Для <b>всего приложения</b>: главная и все доски",
    "Undo": "Отменить",
    "small and big": "малая и большая",
    "paste under the pointer": "вставить под курсор",
    "Each image as its own element": "Каждая картинка отдельным элементом",
    "apply (Enter: new line)": "применить (Enter: новая строка)",
    "loading…": "загрузка…",
    "pointer over a video": "мышь над видео",
    "above a note": "над стикером",
    "copy, cut": "копировать, вырезать",
    "canvas only / with the library": "только холст / вместе с библиотекой",
    "Where I am": "Где я",
    "is linked to every frame under it": "привязан ко всем кадрам под ним",
    "Paper color in the dark theme": "Цвет бумаги в темной теме",
    "Notes": "Заметки",
    ", another page,": ", другая страница,",
    "one row, aligned at the top": "в один ряд по верхнему краю",
    "Pages · double-click to rename": "Страницы · двойной клик: переименовать",
    "Panels and buttons float above the board": "Плашки и кнопки парят над доской",
    "Dark": "Темная",
    "Only liked": "Только с сердечком",
    "Shadows": "Тени",
    "Redo · ⇧⌘Z": "Вернуть · ⇧⌘Z",
    "Timeline · L": "Таймлайн · L",
    "heading": "заголовок",
    "undo, redo": "отменить, вернуть",
    "or": "или",
    "Save": "Сохранить",
    "file missing": "файла нет",
    "Note": "Заметка",
    "Label": "Подпись",
    "Loading": "Загрузка",
    "Language": "Язык",
    "library::{n} frames": "{n} кадров",
    "Show {a} more of {b}": "Показать еще {a} из {b}",
    "yellow": "желтый",
    "orange": "оранжевый",
    "red": "красный",
    "pink": "розовый",
    "purple": "фиолетовый",
    "blue": "синий",
    "green": "зеленый",
    "grey": "серый",
    "Small": "Мелкий",
    "Regular": "Обычный",
    "Large": "Крупный",
    "Heading": "Заголовок",
    "Big heading": "Большой заголовок",
    "Plugin “{name}” did not load: {why}": "Плагин «{name}» не загрузился: {why}",
    "Remove arrow": "Убрать стрелку",
    "Start": "Старт",
    "Area: stretch the edges, the frames inside are linked": "Область: растяни края, кадры внутри привязаны",
    "Area removed": "Область убрана",
    "You": "Ты",
    "AI": "ИИ",
    "auto": "авто",
    "today": "сегодня",
    "yesterday": "вчера",
    "Couldn't open this version": "Эту версию не получилось открыть",
    "Viewing version": "Просмотр версии",
    "Couldn't restore the version": "Не получилось вернуть версию",
    "The board could not redraw: {why}": "Доска не смогла перерисоваться: {why}",
    "You're working in this version. The previous state is saved as the first line of the history": "Работаешь в этой версии. Прежнее состояние сохранено первой строкой истории",
    "Today": "Сегодня",
    "Yesterday": "Вчера",
    "Autosave": "Автосохранение",
    "AI edit": "Правка ИИ",
    "Version": "Версия",
    "{n} frames": ["{n} кадр", "{n} кадра", "{n} кадров"],
    "{n} notes": ["{n} заметка", "{n} заметки", "{n} заметок"],
    "{n} groups": ["{n} группа", "{n} группы", "{n} групп"],
    "{n} frames of this version are no longer on disk": ["{n} кадра этой версии уже нет на диске", "{n} кадров этой версии уже нет на диске", "{n} кадров этой версии уже нет на диске"],
    "Now": "Сейчас",
    "Current version": "Текущая версия",
    "what you're working with": "то, с чем ты работаешь",
    "No versions yet": "Версий пока нет",
    "An autosave with the first change, then <b>every 10 min</b>": "Автосохранение при первом изменении, дальше <b>каждые 10 мин</b>",
    "{n} autosaves": ["{n} автосохранение", "{n} автосохранения", "{n} автосохранений"],
    "fold autosaves": "свернуть автосохранения",
    "before restoring the version {when}": "до возврата к версии {when}",
    "auto snapshot": "автоснимок",
    "version": "версия",
    "Nothing yet": "Пока пусто",
    "Added {n} frames": ["Добавлено {n} кадр", "Добавлено {n} кадра", "Добавлено {n} кадров"],
    "Removed {n} frames": ["Убрано {n} кадр", "Убрано {n} кадра", "Убрано {n} кадров"],
    "New group": "Новая группа",
    "Group deleted": "Группа удалена",
    "Group renamed": "Группа переименована",
    "New note": "Новая заметка",
    "Note changed": "Заметка изменена",
    "Note deleted": "Заметка удалена",
    "New heading": "Новый заголовок",
    "Heading changed": "Заголовок изменен",
    "Heading deleted": "Заголовок удален",
    "New timeline": "Новый таймлайн",
    "Moved": "Перемещено",
    "and": "и",
    "restored a version": "возврат к версии",
    "No changes yet": "Изменений пока нет",
    "Show earlier": "Показать раньше",
    "This was deleted: it is no longer on the canvas": "Это удалили: на холсте этого больше нет",
    "These objects are no longer on the page": "Этих объектов на странице уже нет",
    "Version saved": "Версия сохранена",
    "Not saved: the server didn't answer": "Не сохранилось: сервер не ответил",
    "Drag: line length": "Потяни: длина линии",
    "A copy: this frame is already on the canvas, click to go to the original": "Копия, этот кадр уже есть на холсте: нажми, чтобы перейти к оригиналу",
    "Opacity · keys 1…9 and 0": "Прозрачность · клавиши 1…9 и 0",
    "Opacity": "Прозрачность",
    "As a square block · ⌥A": "Квадратным блоком · ⌥A",
    "Arrange": "Упорядочить",
    "In one row, aligned at the top · ⌥S": "В один ряд по верхнему краю · ⌥S",
    "In a row": "В ряд",
    "Tidy: rows and blocks stay, the gaps become even · ⌥D": "Причесать: строки и блоки остаются, промежутки становятся ровными · ⌥D",
    "Tidy": "Причесать",
    "Smaller text": "Текст меньше",
    "Bigger text": "Текст больше",
    "Horizontal: labels on top": "Горизонтально: подписи сверху",
    "Horizontal": "Горизонтально",
    "Vertical: labels on the left": "Вертикально: подписи слева",
    "Vertical": "Вертикально",
    "Smaller labels": "Подписи меньше",
    "Bigger labels": "Подписи больше",
    "A dashed zone: the frames inside are linked to the note": "Пунктирная зона: кадры внутри привязаны к стикеру",
    "Smaller type": "Шрифт меньше",
    "Bigger type": "Шрифт больше",
    "Free frame: drag the edges and corners": "Свободный кадр: тяни стороны и углы",
    "Free": "Свободно",
    "Turn the frame": "Повернуть кадр",
    "Saving and opening the board in Chromium…": "Сохраняю и открываю доску в Chromium…",
    "Saving and opening the board in WebKit…": "Сохраняю и открываю доску в WebKit…",
    "Group": "Группа",
    "Remove ♥ from the selected": "Снять ♥ с выделенных",
    "♥ on all selected": "♥ на все выделенные",
    "point at the line: + adds a dot": "наведи на линию: + добавит точку",
    "Drag to a frame or group: an arrow": "Потяни к кадру или группе: стрелка",
    "Remove area": "Убрать область",
    "Area": "Область",
    "belongs to the whole group “{name}”: {frames} · goes into these frames' json": "относится ко всей группе «{name}»: {frames} · попадет в json этих кадров",
    "linked: {frames} · goes into these frames' json": "привязан: {frames} · попадет в json этих кадров",
    "not linked": "не привязан",
    "How to link": "Как привязать",
    "To link it: lay it on a frame, draw an arrow from its yellow dot, turn on “Area” or put it inside a group": "Чтобы привязать: положи на кадр, протяни стрелку от желтой точки, включи «Область» или помести внутрь группы",
    "{n} frames · double-click the name to rename": "{n} кадров · двойной клик по названию переименовать",
    "Remove ♥ · F": "Снять ♥ · F",
    "Idea": "Идея",
    "Boring, cliché": "Скучно, шаблон",
    "There, but weak": "Есть, но слабая",
    "Strong idea": "Сильная идея",
    "Humor": "Юмор",
    "Misses": "Мимо",
    "Makes you smile": "Улыбает",
    "Hooks": "Цепляет",
    "Our world": "Наш мир",
    "Not our world": "Не наш мир",
    "Futurism": "Футуризм",
    "A hint": "Намек",
    "Future": "Будущее",
    "Casting": "Кастинг",
    "Wrong faces": "Не те лица",
    "Strong casting": "Сильный кастинг",
    "Costume": "Костюм",
    "Kitsch": "Кич",
    "Stylish": "Стильно",
    "Pose": "Поза",
    "Unmotivated": "Немотивирована",
    "Great": "Крутая",
    "Wrong": "Не тот",
    "Excellent": "Отличный",
    "Color": "Цвет",
    "Color system": "Цветовая система",
    "Composition": "Композиция",
    "Clutter in the frame": "Лишнее в кадре",
    "Phone": "Телефон",
    "Wrong, not visible": "Не тот, не виден",
    "So-so": "Так себе",
    "Right, visible": "Тот, виден",
    "Case": "Чехол",
    "Crooked": "Кривой",
    "Almost": "Почти",
    "Exact": "Точный",
    "Material": "Материал",
    "Plastic, CGI": "Пластик, CGI",
    "Real metal": "Настоящий металл",
    "Take": "Беру",
    "No": "Нет",
    "Ads": "Реклама",
    "Animation": "Анимация",
    "Website": "Сайт",
    "Series": "Серия",
    "Present day": "Сегодняшний день",
    "Rating": "Оценка",
    "♥ Favorite": "♥ Избранное",
    "Marks on the frame: {n}": "Пометок на кадре: {n}",
    "Source": "Источник",
    "Prompt": "Промпт",
    "Show in full": "Показать целиком",
    "Collapse": "Свернуть",
    "in the area": "в области",
    "by an arrow": "стрелкой",
    "lies on the frame": "лежит на кадре",
    "through the group": "через группу",
    "Note from the board": "Заметка с доски",
    "Notes from the board": "Заметки с доски",
    "Go to the note": "Перейти к заметке",
    "Group “{name}”": "Группа «{name}»",
    "Outside groups": "Вне групп",
    "cropped": "обрезан",
    "copies on the page: {n}": "копий на странице: {n}",
    ", in frames {n}": ", во фреймах {n}",
    "On the board": "На доске",
    "Tags": "Теги",
    "References": "Эталоны",
    "open": "открыть",
    "AI questions": "Вопросы ИИ",
    "no answer": "без ответа",
    "video": "видео",
    "{n} MB": "{n} МБ",
    "{n} KB": "{n} КБ",
    "batch": "партия",
    "File": "Файл",
    "Show in Finder": "Показать в Finder",
    "<b>The AI reads</b> this: the frame's json and the board's notes": "<b>Это читает ИИ</b>: json кадра и заметки доски",
    "To the original": "К оригиналу",
    "Back to the duplicate": "Вернуться к дубликату",
    "criterion::Close": "Близко",
    "criterion::Light": "Свет",
    "criterion::Strong": "Сильная",
    "The linked object isn't on this page: it was deleted or is on another one": "Объекта из ссылки нет на этой странице: его удалили или он на другой",
    "Board drawn, waiting for smooth frames": "Доска нарисована, жду ровных кадров",
    "Images: {n} more": "Картинки: еще {n}",
    "Images in place": "Картинки на месте",
    "Page “{name}”": "Страница «{name}»",
    "This frame is on no board": "Этого кадра нет на досках",
    "Copying the image…": "Копирую картинку…",
    "Image copied (with the crop): paste it into Photoshop": "Картинка скопирована (с кадрированием): вставляй в Photoshop",
    "Image copied: paste it into Photoshop": "Картинка скопирована: вставляй в Photoshop",
    "Couldn't copy the image: {why}": "Не получилось скопировать картинку: {why}",
    "Copy link to the selection ({n})": "Копировать ссылку на выделенное ({n})",
    "Copy link to the group": "Копировать ссылку на группу",
    "Copy link to the note": "Копировать ссылку на заметку",
    "Copy link to the text": "Копировать ссылку на текст",
    "Copy link to the 3D scene": "Копировать ссылку на 3D-сцену",
    "Copy link to the object": "Копировать ссылку на объект",
    "Copy link to the frame": "Копировать ссылку на кадр",
    "verb::Group": "Сгруппировать",
    "Ungroup": "Расформировать группу",
    "Group name": "Имя группы",
    "Copy image": "Копировать картинку",
    "Copy file path": "Копировать путь к файлу",
    "Copy link to this view": "Копировать ссылку на этот вид",
    "Link copied: it opens and shows this object": "Ссылка скопирована: откроет и покажет этот объект",
    "File path copied": "Путь к файлу скопирован",
    "Link to this view copied": "Ссылка на этот вид скопирована",
    "♥ set": "♥ поставлен",
    "♥ on {frames}": "♥ на {frames}",
    "♥ removed": "♥ снят",
    "Not saved: the server didn't answer, ♥ is back as it was": "Не сохранилось: сервер не ответил, ♥ вернул как было",
    "This is a version preview. To change it, press “Restore this version”": "Это просмотр версии. Чтобы менять, нажми «Работать в этой версии»",
    "{n} frames went to the archive": ["{n} кадр ушел в архив", "{n} кадра ушли в архив", "{n} кадров ушли в архив"],
    "{frames} back on the canvas": "{frames} снова на холсте",
    "loading images: {n}": "загружаю картинки: {n}",
    "saving…": "сохраняю…",
    "not saving": "не сохраняется",
    "The board is being changed elsewhere: reload the page, or the changes here won't be saved": "Доску меняют в другом месте: обнови страницу, иначе изменения здесь не сохранятся",
    "notes in json: {n}": "заметки в json: {n}",
    "not saved": "не сохранено",
    "Not saved: the server isn't answering. The changes are kept here, I'll save them as soon as it answers": "Не сохранилось: сервер не отвечает. Изменения держатся здесь, сохраню, как только он ответит",
    "Board updated": "Доска обновилась",
    "added {n}": "добавлено {n}",
    "removed {n}": "убрано {n}",
    "adding the image…": "добавляю картинку…",
    "adding {frames}…": "добавляю {frames}…",
    "saving the image…": "сохраняю картинку…",
    "saving {frames}…": "сохраняю {frames}…",
    "Added: {frames}, the files are in the folder {folder}": "Добавлено: {frames}, файлы в папке {folder}",
    "not added": "не добавлено",
    "saved": "сохранено",
    "Image added": "Картинка добавлена",
    "Added: {frames}": "Добавлено: {frames}",
    "Put {frames} on the canvas? It takes room and memory.": "Положить на холст {frames}? Это займет место и память.",
    "placing {what}…": "кладу {what}…",
    "{n} folders, ": "{n} папки, ",
    "Placed: {what}": "Положено: {what}",
    ", already on the canvas: {n}": ", уже были на холсте: {n}",
    "Already on the canvas: {n}, marked as a copy": "Уже есть на холсте: {n}, отмечен как копия",
    "Already on the canvas: {n}, marked as copies": "Уже есть на холсте: {n}, отмечены как копия",
    "Arrow: to the group, all its frames are linked": "Стрелка: к группе, все ее кадры привязаны",
    "Arrow: to the frame": "Стрелка: к кадру",
    "What you liked here. ⌘B bold, - list": "Что здесь понравилось. ⌘B жирный, - список",
    "The frame fits its contents": "Рамка подогнана под содержимое",
    "No frames in the area, nothing to fit to": "В области нет кадров, подгонять не к чему",
    "crop::Free frame": "Свободная рамка",
    "Turn the ratio · X": "Повернуть пропорцию · X",
    "With sound · Space": "Со звуком · Пробел",
    "Play with sound": "Играть со звуком",
    "Drag: seek": "Потяни: перемотка",
    "Divider: right-click to delete": "Разделитель: правый клик, чтобы удалить",
    "New page": "Новая страница",
    "The area fits the frames": "Область подогнана под кадры",
    "Group {n}": "Группа {n}",
    "Copied {n}. The clipboard holds a link; for the image: ⇧⌘C": "Скопировано {n}. В буфере ссылка, картинка: ⇧⌘C",
    "Cut: {frames}, ⌘V pastes them on any page": "Вырезано: {frames}, ⌘V вставит на любой странице",
    "Pasted: {frames}": "Вставлено: {frames}",
    "Pause · Space": "Пауза · Пробел",
    "Pause": "Пауза",
    "The video is small on screen: zoom in, or open it full screen with ⤢ in its pill": "Видео мелкое на экране: приблизь его или открой во весь экран кнопкой ⤢ на плашке",
    "The browser didn't allow sound: press ▶ on the video": "Браузер не дал включить звук: нажми ▶ на видео",
    "preparing the video": "готовлю видео",
    "Select an image": "Выдели картинку",
    "The group is bigger than the screen, its selection is paused. Zoom out to delete or cut it": "Группа больше экрана, ее выделение на паузе. Отдали, чтобы удалить или вырезать",
    "new page": "новая страница",
    "The page list wasn't saved": "Список страниц не сохранился",
    "This is the only page, it can't be deleted": "Это единственная страница, ее нельзя удалить",
    "Delete the page “{name}”? It holds {frames}. The page's file goes to boards/_deleted and can be brought back": "Удалить страницу «{name}»? На ней {frames}. Файл страницы уйдет в boards/_deleted, его можно вернуть",
    "Only an empty page can become a divider, this one holds {frames}": "Разделителем может стать только пустая страница, на этой {frames}",
    "Delete divider": "Удалить разделитель",
    "Rename…": "Переименовать",
    "Delete page": "Удалить страницу",
    "Copy folder path": "Скопировать путь к папке",
    "Rename board…": "Переименовать доску…",
    "Board folder path copied": "Путь к папке доски скопирован",
    "Reading the board's pages": "Читаю страницы доски",
    "Opening the page “{name}”": "Открываю страницу «{name}»",
    "The page holds {frames}, reading the library": "На странице {frames}, читаю библиотеку",
    "Library: {frames}, drawing the board": "Библиотека: {frames}, рисую доску",
    "Page {n}": "Страница {n}",
    "{n} on the canvas": "на холсте {n}",
    "Hide “No”": "без «Нет»",
    "“{t}”": "«{t}»",
    "frame {t}": "кадр {t}",
    "The frame's json has no link to its source": "в json кадра нет ссылки на источник",
    "Couldn't read the frame's json": "не удалось прочитать json кадра",
    "3D and recolor": "3D и перекраска",
    "Engine not set": "Движок не указан",
    "level::Fine": "Нормально",
    // crop & trim of a video, the full-screen player, the board renamed in place (owner 2026-10-06)
    "Crop the picture, trim the start and the end · C": "Кадрировать, обрезать начало и конец · C",
    "Crop · C": "Кадрировать · C",
    "Crop & Trim": "Кроп и обрезка",
    "Crop": "Кроп",
    "Full screen": "Во весь экран",
    "Drag the yellow handles: where it starts and ends": "Тяни желтые ручки: где начало и где конец",
    "{n} s": "{n} с",
    "Crop and trim: the yellow handles set the start and the end ·": "Кроп и обрезка: желтые ручки задают начало и конец ·",
    "cancel": "отмена",
    "Board name": "Название доски",
    "the media library: open, close": "медиатека: открыть, закрыть",
    "hide all the interface, again: bring it back": "скрыть весь интерфейс, еще раз: вернуть",
    "Interface hidden · ⌘. to show": "Интерфейс скрыт · ⌘. чтобы вернуть",
    "Previous page": "Предыдущая страница",
    "Next page": "Следующая страница",
    "Previous page · ←": "Предыдущая страница · ←",
    "Next page · →": "Следующая страница · →",
    "Preview": "Просмотр",
    "PDF": "PDF",
    "{n} pages": ["{n} страница", "{n} страницы", "{n} страниц"],
    "p. {n}": "стр. {n}",
    "Split into pages · ⌥P": "Разделить на страницы · ⌥P",
    "Split into pages ({n})": "Разделить на страницы ({n})",
    "This PDF has one page": "В этом PDF одна страница",
    "Split into {n} pages?": ["Разделить на {n} страницу?", "Разделить на {n} страницы?", "Разделить на {n} страниц?"],
    "{n} empty files stay in the library: there is nothing to place": ["{n} пустой файл остается в библиотеке: класть нечего", "{n} пустых файла остаются в библиотеке: класть нечего", "{n} пустых файлов остаются в библиотеке: класть нечего"],
    // the dock's mode switch (ui/modes.js, owner 2026-10-06); the plugins' modes have their words in their own lang.js
    "Board": "Доска",
    "Mode": "Режим",
    "Board: every card, the canvas itself": "Доска: все карточки, сам холст",
    // «Move to page ›» in the board's right-click menu (owner 2026-10-06)
    "Move to page": "Переместить на страницу",
    "New page…": "Новая страница…",
    "Moved to “{page}”: {n} objects": "Перенесено на «{page}»: {n}",
    "arrows dropped: {n}": "убрано стрелок: {n}",
    "The board isn't saved yet, nothing was moved": "Доска еще не сохранена, ничего не перенесено",
    "Before: moved to “{page}”": "До: перенос на «{page}»",
    "After: moved to “{page}”": "После: перенос на «{page}»",
    "Before: moved from “{page}”": "До: перенос с «{page}»",
    "After: moved from “{page}”": "После: перенос с «{page}»",
    "moved from “{page}”": "перенос с «{page}»",
    "moved back to “{page}”": "возврат на «{page}»",
    "moved back from “{page}”": "возврат с «{page}»",
    "The move is undone: “{page}” is as it was": "Перенос отменен: «{page}» как было",
    "Couldn't move: {why}": "Не получилось перенести: {why}",
    // «Copy properties ›» and «Paste properties ›» (owner 2026-10-06)
    "Copy properties": "Копировать свойства",
    "Paste properties": "Вставить свойства",
    "props::Crop": "Обрезка",
    "props::Time": "Время",
    "props::Size": "Размер",
    "props::Opacity": "Прозрачность",
    "props::PDF page": "Страница PDF",
    "Custom…": "Выборочно…",
    "Save as preset…": "Сохранить как пресет…",
    "Save as preset": "Сохранить как пресет",
    "Presets": "Пресеты",
    "Preset name": "Название пресета",
    "All": "Все",
    "verb::Copy": "Копировать",
    "from {name}: {what}": "из {name}: {what}",
    "Crop only on images and videos": "Обрезка только у картинок и видео",
    "Time only on videos": "Время только у видео",
    "A timeline has no size to take": "У таймлайна нет размера",
    "Opacity only on images, videos and cards": "Прозрачность только у картинок, видео и карточек",
    "A page only on a PDF that is not split": "Страница только у неразделенного PDF",
    "Does not apply": "Не подходит",
    "Nothing to copy: this object has none of these properties": "Копировать нечего: у объекта нет этих свойств",
    "Copied properties: {what}": "Скопированы свойства: {what}",
    "These properties don't apply to the selection": "Эти свойства не подходят выделенному",
    "Pasted {what} on {n} objects": ["Вставлено на {n} объект: {what}", "Вставлено на {n} объекта: {what}", "Вставлено на {n} объектов: {what}"],
    "Preset “{name}” saved: {what}": "Пресет «{name}» сохранен: {what}",
    "Select an object to copy its properties": "Выдели объект, чтобы скопировать его свойства",
    "No properties copied yet: ⌥⌘C": "Свойства еще не скопированы: ⌥⌘C",
    // a menu item that does not apply here is grey with its reason (owner 2026-10-06: «I want users to know what functions exist»)
    "Select one file": "Выдели один файл",
    "Only for a file": "Только для файла",
    "Groups are not grouped: select the objects": "Группы не группируются: выдели объекты",
    "No group selected": "Группа не выделена",
    "This board has no pages": "У этой доски нет страниц",
    "Split into pages": "Разделить на страницы",
    "Select one PDF": "Выдели один PDF",
    "Only for a PDF": "Только для PDF",
    "This is already one page of a PDF": "Это уже одна страница PDF",
    "Counting the PDF's pages": "Считаю страницы PDF",
    "No file in the selection": "В выделенном нет файлов",
    "This picture isn't cropped": "Картинка не обрезана",
    "This video isn't trimmed": "Видео не обрезано по времени",
    "This object is fully opaque": "Объект полностью непрозрачный",
    "Nothing selected": "Ничего не выделено",
    "This object has no “{what}”": "У объекта нет свойства «{what}»",
    "Nothing to copy from this object": "Копировать нечего",
    "Not in the clipboard": "Нет в буфере",
    "The clipboard is empty": "Буфер пуст",
    "No presets yet: “Save as preset…” in Copy properties": "Пресетов нет: «Сохранить как пресет…» в «Копировать свойства»",
    // «Order ›» (owner 2026-10-06, as in Figma)
    "Order": "Порядок",
    "Bring to front": "На передний план",
    "Bring forward": "Выше",
    "Send backward": "Ниже",
    "Send to back": "На задний план",
    "Already on top": "Уже сверху",
    "Already at the bottom": "Уже снизу",
    "No neighbours in the group": "Нет соседей в группе",
    "Nothing else on this level": "Больше ничего на этом уровне",
    "bring forward, send backward": "выше, ниже",
    "to the front, to the back": "на передний план, на задний план",
    // the clipboard on the right click (owner 2026-10-07)
    "Cut": "Вырезать",
    "Paste": "Вставить",
    "Paste here": "Вставить сюда",
    "Duplicate": "Дублировать",
    "Remove from the board": "Удалить с доски",
    "Nothing to copy": "Копировать нечего",
    "A group is duplicated by its cards: select them": "Группа дублируется по карточкам: выдели их",
    "Zoom out: the group is bigger than the screen": "Отдали: группа больше экрана",
    // the arrows nudge the selection (owner 2026-10-07): the shortcuts panel's line
    "move the selection a little, with": "сдвинуть выделенное чуть-чуть, с",
    "more": "сильнее",
  },
});
