// The Russian words of the library (review/v2.html) and the old tag page (review/index.html); the English text in the code is the key (ui/i18n.js says how).
// en: only plurals and context keys ("ctx::Text").
hyLang({
  en: {
    "{n} files here are empty": ["{n} file here is empty", "{n} files here are empty"],
    "{n} files in all folders are empty": ["{n} file in all folders is empty", "{n} files in all folders are empty"],
    "{n} folders": ["{n} folder", "{n} folders"],
    "{n} frames": ["{n} frame", "{n} frames"],
    "Questions waiting for an answer: {n} frames": ["Questions waiting for an answer: {n} frame", "Questions waiting for an answer: {n} frames"],
  },
  ru: {
    "The folder's colour was not saved": "Цвет папки не сохранился",
    "Old page": "старая страница",
    "Galleries": "Галереи",
    "Previous collection": "Предыдущая коллекция",
    "Next collection": "Следующая коллекция",
    "Collection": "Коллекция",
    "All collections": "Все коллекции",
    "Rating": "Оценка",
    "All": "Все",
    "New": "Новые",
    "Take": "Беру",
    "Idea": "Идея",
    "No": "Нет",
    "Liked": "Избранное",
    "Questions": "Вопросы",
    "My questions: what did you mean": "Мои вопросы: что ты имел в виду",
    "Material: real metal": "Материал: настоящий металл",
    "Metal": "Металл",
    "Exact case": "Чехол точный",
    "Exact": "Точный",
    "3D": "3D",
    "3D files of the library: they turn under the pointer": "3D-файлы библиотеки: поворачиваются под курсором",
    "converting…": "преобразуется…",
    "FreeCAD is needed to read STEP files": "Для чтения STEP нужен FreeCAD",
    "The file is empty": "Файл пустой",
    "The file is too big to convert": "Файл слишком большой для преобразования",
    "FreeCAD took too long on this file": "FreeCAD слишком долго читает этот файл",
    "No solids in the file": "В файле нет тел",
    "FreeCAD could not read this file": "FreeCAD не смог прочитать этот файл",
    // a 3D file in the viewer (ui/lib3d.js and the 3D plugin's viewer.js, 2026-10-07)
    "Drag to turn · scroll to zoom": "Тяни, чтобы повернуть · колесо приближает",
    "Put on the board": "На доску",
    "A 3D card of this file on the board: turn it, light it, render it in 3D Studio": "3D-карточка этого файла на доске: поворот, свет и рендер в 3D Studio",
    "The 3D plugin shows 3D files: it is not installed": "3D-файлы показывает плагин «3D-объекты», он не установлен",
    "FreeCAD converts the file into a 3D model…": "FreeCAD превращает файл в 3D-модель…",
    "Loading the 3D model…": "Загружаю 3D-модель…",
    "Too many triangles to show here: {n} million": "Слишком много треугольников для просмотра: {n} млн",
    "This 3D file cannot be shown": "Этот 3D-файл не получается показать",
    "The file is over {n} MB": "Файл больше {n} МБ",
    "case": "чехол",
    "Search": "Поиск",
    "Filter by tags": "Фильтр по тегам",
    "Show rejects": "Показывать брак",
    "Rejects": "Брак",
    "Reset filters and show all collections": "Сбросить фильтры и показать все коллекции",
    "Reset filters": "Сбросить фильтры",
    "Reset": "Сбросить",
    "Folders": "Папки",
    "Find folder": "Найти папку",
    "Rejected": "Отклоненные", "Only rejected": "Только отклоненные",
    "The «_rejected» folder: a click shows them with the rest, the next shows them alone": "Папка «_rejected»: клик показывает их вместе со всеми, следующий только их",
    "Drag to make the folders wider or narrower": "Потяни, чтобы сделать папки шире или уже",
    "Canvas": "Холст",
    "Frame actions": "Действия с кадром",
    "Select all visible frames · ⌘A": "Выбрать все видимые кадры · ⌘A",
    "Select all": "Выбрать все",
    "Deselect · Esc": "Снять выбор · Esc",
    "Deselect": "Снять выбор",
    "Click: show": "Клик: показать",
    "Filters": "Фильтры",
    "Kind": "Тип",
    "Images": "Картинки",
    "Video": "Видео",
    "Score: {name}": "Оценка: {name}",
    "Pin to the bar": "Закрепить на панели",
    "Unpin from the bar": "Открепить с панели",
    "The pins could not be saved": "Не получилось сохранить закрепленные фильтры",
    "Add a tag": "Добавить тег",
    "Tag name": "Название тега",
    "Words to find, separated by commas": "Слова для поиска через запятую",
    "Group": "Группа",
    "Own tags": "Свои теги",
    "Add": "Добавить",
    "Adding…": "Добавляю…",
    "Give the tag a name and the words to find": "Назови тег и укажи слова для поиска",
    "This tag already exists": "Такой тег уже есть",
    "The tag was not saved: check the name and the words": "Тег не сохранен: проверь название и слова",
    "Tag «{tag}» added": "Тег «{tag}» добавлен",
    ", click again: exclude": ", еще клик: исключить",
    ", third: clear": ", третий: снять",
    "Reset tags": "Сбросить теги",
    "Drag to resize the library": "Потяни, чтобы изменить ширину библиотеки",
    "Library · ⌘M": "Библиотека · ⌘M",
    "Library": "Библиотека",
    "Card view and size": "Вид карточек и их размер",
    "Card view": "Вид карточек",
    "View": "Вид",
    "Square grid": "Квадратная сетка",
    "Rows of one height, each image keeps its proportions": "Ряды одной высоты, у каждой картинки своя пропорция",
    "Rows of one height": "Ряды одной высоты",
    "Size": "Размер",
    "Card size": "Размер карточек",
    "Full-width library": "Библиотека во всю ширину",
    "Normal-width library": "Библиотека обычной ширины",
    "Frame viewer": "Просмотр кадра",
    "<b>Drag</b> over an area to comment · edit under <b>“Marks”</b>": "<b>Выдели</b> область, чтобы прокомментировать · правка в <b>«Пометках»</b>",
    "Marks": "Пометки",
    "Show or hide marks · N": "Показать или скрыть пометки · N",
    "What is wrong here, or what is great": "Что здесь не так или что круто",
    "Delete": "Удалить",
    "Done": "Готово",
    "Previous": "Предыдущий",
    "Next": "Следующий",
    "Shortcuts": "Клавиши",
    "Close": "Закрыть",
    "next block: criteria, “Good for”, marks, comment ·": "следующий блок: критерии, «Годится для», пометки, комментарий ·",
    "score": "оценка",
    "not about this frame ·": "не про этот кадр ·",
    "row": "строка",
    "take ·": "беру ·",
    "rework ·": "доработать ·",
    "no ·": "нет ·",
    "♥ like": "♥ избранное",
    "Drag over an area: a comment · click a box: edit ·": "Выдели область: комментарий · щелчок по рамке: правка ·",
    "hide marks": "скрыть пометки",
    "frame ·": "кадр ·",
    "comment ·": "комментарий ·",
    "close": "закрыть",
    "Zoom: pinch on the trackpad, move with two fingers": "Зум: щипок на тачпаде, двумя пальцами двигать",
    "Rework": "Доработать",
    "Like": "В избранное",
    "Like · R": "В избранное · R",
    "Good for": "Годится для",
    "Notes from the board": "Заметки с доски",
    "Marks on the frame": "Пометки на кадре",
    "Comment: what to fix, where to take it": "Комментарий: что поправить, куда развивать",
    "After “Take”, “Rework” or “No”, go straight to the next frame": "После «Беру», «Доработать» или «Нет» сразу следующий кадр",
    "Prompt and references": "Промпт и эталоны",
    "Humor": "Юмор",
    "Our world": "Наш мир",
    "Futurism": "Футуризм",
    "Casting": "Кастинг",
    "Costume": "Костюм",
    "Pose": "Поза",
    "Light": "Свет",
    "Color": "Цвет",
    "Composition": "Композиция",
    "Phone": "Телефон",
    "Case": "Чехол",
    "Material": "Материал",
    "Boring, cliché": "Скучно, шаблон",
    "There, but weak": "Есть, но слабая",
    "Strong idea": "Сильная идея",
    "Misses": "Мимо",
    "Makes you smile": "Улыбает",
    "Hooks": "Цепляет",
    "Not our world": "Не наш мир",
    "world::Close": "Близко",
    "Present day": "Сегодняшний день",
    "A hint": "Намек",
    "Future": "Будущее",
    "Wrong faces, anatomy": "Не те лица, анатомия",
    "Fine": "Нормально",
    "Strong casting": "Сильный кастинг",
    "Kitsch": "Кич",
    "Stylish": "Стильно",
    "Unmotivated": "Немотивирована",
    "Great": "Крутая",
    "Wrong, warm, old money": "Не тот, теплый, old money",
    "Excellent": "Отличный",
    "Wrong": "Не тот",
    "Color system": "Цветовая система",
    "Clutter in the frame": "Лишнее в кадре",
    "Strong": "Сильная",
    "Wrong, not visible": "Не тот, не виден",
    "So-so": "Так себе",
    "Right, visible": "Тот, виден",
    "Crooked": "Кривой",
    "Almost": "Почти",
    "Plastic, CGI": "Пластик, CGI",
    "Real metal": "Настоящий металл",
    "Boring": "Скучно",
    "Weak": "Слабая",
    "Smiles": "Улыбает",
    "Not ours": "Не наш",
    "Ours": "Наш",
    "casting::Wrong": "Не те",
    "OK": "Норм",
    "casting::Strong": "Сильный",
    "Today": "Сегодня",
    "pose::Wrong": "Не та",
    "System": "Система",
    "Clutter": "Лишнее",
    "Plastic": "Пластик",
    "Right": "Тот",
    "People": "Люди",
    "Image": "Картинка",
    "Product": "Продукт",
    "Ads": "Реклама",
    "Animation": "Анимация",
    "Website": "Сайт",
    "Series": "Серия",
    "New frames in the library: {n}": "В библиотеке новые кадры: {n}",
    "External": "Внешние",
    "Added by hand": "Добавлено вручную",
    "Board root": "В корне доски",
    "drag onto the canvas to place the folder as a block": "перетащи на холст: папка встанет блоком",
    "Collapse": "Свернуть",
    "Expand": "Развернуть",
    "Mark folder": "Отметить папку",
    "Marked with the folder above": "Отмечена вместе с папкой выше",
    "Mark: marked folders are dragged onto the canvas together": "Отметить: отмеченные папки перетаскиваются на холст вместе",
    "All folders": "Все папки",
    "Hide folders": "Свернуть папки",
    "Show folders": "Открыть папки",
    "Marked folders are dragged onto the canvas together": "Отмеченные папки перетаскиваются на холст вместе",
    "Clear marks": "Снять отметки",
    "clear": "снять",
    "{n} folders": ["{n} папка", "{n} папки", "{n} папок"],
    "{n} frames": ["{n} кадр", "{n} кадра", "{n} кадров"],
    "On the canvas": "На холсте",
    "Archived": "В архиве",
    "Has a comment": "Есть комментарий",
    "Has marks on the frame": "Есть пометки на кадре",
    "Has a question": "Есть вопрос",
    "Has criteria scores": "Есть оценки по критериям",
    "Not reviewed": "Не разобран",
    "3D and recolor": "3D и перекраска",
    "Engine not set": "Движок не указан",
    "Engine": "Движок",
    "Review": "Разбор",
    "Changed": "Изменено",
    "pill::New": "Новое",
    "QA: rejected": "QA: брак",
    "Archived: taken off the canvas, left out of the work and the AI's context": "В архиве: убран с холста, в работу и в контекст ИИ не берется",
    "Questions waiting for an answer: {n} frames": ["Вопросы ждут ответа: {n} кадр", "Вопросы ждут ответа: {n} кадра", "Вопросы ждут ответа: {n} кадров"],
    "All questions answered": "Все вопросы отвечены",
    "Batch {when}": "Партия {when}",
    "{n} new": ["{n} новый", "{n} новых", "{n} новых"],
    "all viewed": "все просмотрено",
    "Nothing matches these filters": "Под эти фильтры ничего не попало.",
    "Shown {shown} of {total} · viewed {done} · new {fresh}": "показано {shown} из {total} · просмотрено {done} · новых {fresh}",
    "Rejects are a folder of their own: choose “All collections” or the “Rejects” collection": "Брак лежит отдельной папкой: выбери «Все коллекции» или коллекцию «Брак»",
    "My check": "Моя проверка",
    "rejected ({reasons})": "брак ({reasons})",
    "passed": "прошел",
    "the critic doubts: {list}": "критик сомневается: {list}",
    "{n} of {total}": "{n} из {total}",
    "on the canvas": "на холсте",
    "archived": "в архиве",
    "Saved {when}": "сохранено {when}",
    "under a note": "под стикером",
    "in a note's area": "в области стикера",
    "arrow": "стрелка",
    "a note for the whole group": "стикер на всю группу",
    "group: {name}": "группа: {name}",
    "page {name}": "страница {name}",
    "No prompt: the frame has no json description": "Промпта нет: кадр без json-описания.",
    "open": "открыть",
    "Saving…": "сохраняю…",
    "Saved to the frame's json · {when}": "сохранено в json кадра · {when}",
    "Rating cleared": "оценка снята",
    "Not saved: the server is not responding, try again": "не сохранилось: сервер не отвечает, попробуй еще раз",
    "Remove": "Убрать",
    "Questions from Claude": "Вопросы от Claude",
    "waiting for an answer: {n}": "ждут ответа: {n}",
    "all answered": "все отвечены",
    "Answer in your own words": "Ответ текстом, как есть",
    "Answer saved {when}": "ответ сохранен {when}",
    "Answer is empty": "ответ пустой",
    "Not saved: the server is not responding": "не сохранилось: сервер не отвечает",
    "{n} selected": "Выбрано {n}",
    "Select all {n}": "Выбрать все {n}",
    "Show on board": "Показать на доске",
    "This frame is on no board": "Этого кадра нет на досках",
    "Show in Finder ({n})": "Показать в Finder ({n})",
    "Show in Finder": "Показать в Finder",
    "Comment on area {n}": "Комментарий к области {n}",
    "Delete mark {n}": "Удалить пометку {n}",
    "Mark {n}": "Пометка {n}",
    "box": "рамка",
    "marker": "маркер",
    "Search by name or prompt": "Поиск по имени или промпту",
    "v1::Show rejects": "показывать брак",
    "Idea, rework": "Идея, доработать",
    "What works": "Что хорошо",
    "What does not": "Что плохо",
    "Comment": "Комментарий",
    "What you liked, what to fix, where to take it": "Что понравилось, что поправить, куда развивать",
    "v1::Open the next frame after rating": "после оценки открывать следующий",
    "Prompt, model, references": "Промпт, модель, эталоны",
    "← → browse · 1 2 3 rate · 0 clear · C comment · Esc close": "← → листать · 1 2 3 оценка · 0 снять · C комментарий · Esc закрыть",
    "Viewed {done} of {total} · new {fresh}": "просмотрено {done} из {total} · новых {fresh}",
    "Emotion": "Эмоция",
    "For ads": "Для рекламы",
    "For animation": "Для анимации",
    "Natural": "Натурально",
    "Bright, for ads": "Ярко, для рекламы",
    "Crooked case": "Чехол кривой",
    "Wrong phone": "Телефон не тот",
    "Phone not visible": "Телефон не виден",
    "Space": "Пространство",
    "Anatomy": "Анатомия",
    "Warm / old money": "Теплый / old money",
    "Cliché": "Шаблон",
    "Plastic / CGI": "Пластик / CGI",
    "Wrong color": "Цвет не тот",
    "Edges / mask": "Края / маска",
    "Wrong camera block": "Блок камер не тот",
    "Empty file · 0 bytes": "Пустой файл · 0 байт",
    "Empty file · cannot be read": "Пустой файл · не читается",
    "{n} files here are empty": ["{n} файл здесь пуст", "{n} файла здесь пусты", "{n} файлов здесь пусты"],
    "{n} files in all folders are empty": ["{n} файл во всех папках пуст", "{n} файла во всех папках пусты", "{n} файлов во всех папках пусты"],
    "This file is empty: there is nothing to open or to put on the board": "Файл пустой: открывать и класть на доску нечего",
    "Pages": "Страницы",
    "Previous page": "Предыдущая страница",
    "Next page": "Следующая страница",
    "Previous page · PageUp": "Предыдущая страница · PageUp",
    "Next page · PageDown": "Следующая страница · PageDown",
    // the Library beside the board, round 15 (ui/libpanel.js, 2026-10-10)
    "Filter": "Фильтр",
    "Fold into the path": "Свернуть в путь",
    "Filters on: {n}": "Включено фильтров: {n}",
    "Search {n} items": "Поиск среди {n}",
    "This picture is on no board": "Этой картинки нет на досках",
    "Show on board ({n})": "Показать на доске ({n})",
  },
});
