// The Russian words of the shared modules of review/ui (menu, toasts, projicon, video, layout-sync, keyhints); the English text in the code is the key (ui/i18n.js says how).
// en: only plurals and context keys ("ctx::Text").
hyLang({
  en: {
    "{n} files": ["{n} file", "{n} files"],
    "{n} images are in several places on the board": ["{n} image is in several places on the board", "{n} images are in several places on the board"],
    "{who} merged {n} changes": ["{who} merged {n} change", "{who} merged {n} changes"],
  },
  ru: {
    // menu.js: «Показать в Finder» for library files
    "Opened 5 folders, {n} more not opened": "Открыты 5 папок, еще {n} не открыты",
    "This file is outside the library": "Этот файл вне библиотеки",
    "The file is not there, or the server was not restarted": "Файла нет на месте или сервер не перезапущен",
    "Finder did not open": "Finder не открылся",
    // menu.js: «Open in <App>» on a card's menu (owner 2026-10-06)
    "Open in default app": "Открыть в программе по умолчанию",
    "Open in {app}": "Открыть в {app}",
    // ui/hy/actions.js, ui/hy/openin.js: a Studio's actions top right, «Open in <Browser>» (owner 2026-10-09)
    "Studio actions": "Действия студии", "Open in browser": "Открыть в браузере", "Choose a browser": "Выбрать браузер",
    "Open the page in {app}": "Открыть страницу в {app}", "Open the page in a new tab": "Открыть страницу в новой вкладке",
    "browser::Default": "По умолчанию", "The page did not open: {why}": "Страница не открылась: {why}",
    "The file did not open": "Файл не открылся",
    // menu.js: the marking colours (a folder in the library's tree, a node in the 3D editor's tree)
    "Colour": "Цвет",
    "No colour": "Без цвета",
    "yellow": "желтый", "orange": "оранжевый", "red": "красный", "pink": "розовый", "purple": "фиолетовый", "blue": "синий", "green": "зеленый", "grey": "серый",
    // toasts.js
    "Close": "Закрыть",
    "Close notification": "Закрыть уведомление",
    // projicon.js: a project's icon picker
    "Icon": "Иконка",
    "Emoji": "Эмодзи",
    "Text color": "Цвет текста",
    "Custom": "Свой",
    "paste or ⌃⌘Space": "вставь или ⌃⌘Пробел",
    // video.js
    "This engine does not play H.264, ffmpeg is needed": "Этот движок не проигрывает H.264, нужен ffmpeg",
    "This video did not load": "Это видео не загрузилось",
    "This video does not play: ffmpeg could not read it": "Это видео не играет: ffmpeg не смог его прочитать",
    "This video does not play in this browser: its format or codec": "Это видео не играет в этом браузере: формат или кодек",
    // layout-sync.js: folders like the board
    "{n} files": ["{n} файл", "{n} файла", "{n} файлов"],
    "Folders on disk follow the board: every board edit arranges the files again. Click for the menu, where you can turn it off": "Папки на диске повторяют доску: каждая правка доски раскладывает файлы заново. Клик: меню, там можно выключить",
    "Like the board": "Как на доске",
    "Folders like the board": "Папки как на доске",
    "Folders arranged like the board: {files}": "Папки разложены как на доске: {files}",
    "Couldn't arrange the folders: ": "Не получилось разложить по папкам: ",
    "run::Couldn't arrange the folders: ": "Не удалось разложить по папкам: ",
    "Arrange folders like the board…": "Разложить по папкам как на доске…",
    "Always keep folders like the board": "Всегда держать папки как на доске",
    "Undo the last layout": "Отменить последнюю раскладку",
    "Folders will follow the board: after every board edit the files arrange themselves": "Папки будут повторять доску: после каждой правки доски файлы разложатся сами",
    "Folders no longer follow the board": "Папки больше не следуют за доской",
    "Couldn't switch the mode: ": "Не удалось переключить режим: ",
    "Layout undone: {files} back in place": "Раскладка отменена: {files} на прежних местах",
    ", {n} not found": ", не нашлось {n}",
    ". “Like the board” mode is off": ". Режим «как на доске» выключен",
    "Couldn't undo the layout: ": "Не удалось отменить раскладку: ",
    "Arrange folders like the board": "Разложить по папкам как на доске",
    "Looking at the board and folders…": "Смотрю доску и папки…",
    "Couldn't work out the layout: ": "Не удалось посчитать раскладку: ",
    "before": "было",
    "after": "стало",
    "“{name}”": "«{name}»",
    "The image files will move on disk into folders by the board's pages, groups and notes{pages}. New folders will appear, and old ones left without a single file will be deleted. The board, frames and old links will keep opening the images. You can undo it in this same menu.": "Файлы картинок переедут на диске в папки по страницам, группам и заметкам доски{pages}. Появятся новые папки, а старые, в которых не останется ни одного файла, будут удалены. Доска, фреймы и старые ссылки продолжат открывать картинки. Отменить можно в этом же меню.",
    " (pages {list})": " (страницы {list})",
    "will move": "переедут",
    "new folders": "новых папок",
    "empty folders deleted": "пустых папок удалим",
    "stay in place": "останутся на месте",
    "For example": "Например",
    "Every image on the board is already in its folder.": "Все картинки с доски уже лежат в своих папках.",
    "Their json files move with the images ({files}).": "Вместе с картинками едут их json ({files}).",
    "Matching names for {files}: the folder each came from is added to the name.": "Совпали имена у {files}: к имени добавится папка, откуда файл пришел.",
    "{n} images are in several places on the board": ["{n} картинка лежит в нескольких местах доски", "{n} картинки лежат в нескольких местах доски", "{n} картинок лежат в нескольких местах доски"],
    "it will go": "она ляжет",
    "they will go": "они лягут",
    "into the folder “{name}” at the project root": "в папку «{name}» в корне проекта",
    "into the project root": "в корень проекта",
    "Files not on any board ({n}) are left alone.": "Файлы, которых нет на досках ({n}), не трогаем.",
    "On: every board edit arranges the files again. Off: only now, once": "Включено: каждая правка доски раскладывает файлы заново. Выключено: только сейчас, один раз",
    "Cancel": "Отмена",
    "folders::Arrange": "Разложить",   // the folders laid out like the board; the selection bar's «Arrange» is «Упорядочить» (lang-board.js)
    "Arranging…": "Раскладываю…",
    "Arranged: {files}": "Разложено: {files}",
    ", new folders: {n}": ", новых папок {n}",
    ", empty ones deleted: {n}": ", удалено пустых {n}",
    ". Folders will follow the board": ". Папки будут повторять доску",
    "Everything is already like the board. Folders will follow the board": "Все уже лежит как на доске. Папки будут повторять доску",
    "Everything is already like the board": "Все уже лежит как на доске",
    // storage.js: Settings › Storage (2026-10-07)
    "{n} GB": "{n} ГБ", "{n} MB": "{n} МБ", "{n} KB": "{n} КБ",
    "Storage": "Хранилище",
    "Measuring…": "Считаю…",
    "Measuring the folders…": "Считаю папки…",
    "Not measured yet": "Еще не посчитано",
    "Boards": "Доски",
    "Made by Hyimg": "Создано Hyimg",
    "Thumbnails, previews and stills in the boards' folders: Hyimg draws them again": "Миниатюры, превью и кадры в папках досок: Hyimg нарисует их заново",
    "Cache": "Кэш",
    "Clear {size}": "Очистить {size}",
    "Nothing to clear": "Нечего очищать",
    "App copies · {n}": "Копии приложения · {n}",
    "To the Trash": "В корзину",
    "Duplicates": "Повторы",
    "Identical files in a board's folder: the space the extra copies take": "Одинаковые файлы в папке доски: сколько места занимают лишние копии",
    "Memory now": "Память сейчас",
    "Graphics": "Графика", "Pages": "Страницы", "Servers": "Серверы", "Window": "Окно", "Services": "Службы", "Scan": "Подсчет", "Other": "Другое", "Blender": "Blender",
    "Server memory": "Память сервера",
    "«Clear» removes <b>only Hyimg's own cache</b>, never your files": "«Очистить» удаляет <b>только кэш Hyimg</b>, ваши файлы не трогает",
    "Clear the cache, {size}?": "Очистить кэш, {size}?",
    "Video copies, 3D conversions and folders of removed boards. Hyimg makes them again when needed": "Копии видео, переводы 3D и папки удаленных досок. Hyimg сделает их заново, когда понадобятся",
    "Clear": "Очистить",
    "Move {n} old app copies to the Trash?": "Старые копии приложения в корзину: {n}?",
    "The 2 newest stay. They can be put back from the Trash": "2 новые останутся. Из корзины их можно вернуть",
    "Nothing was deleted: {why}": "Ничего не удалено: {why}",
    "Freed {size}": "Освобождено {size}",
    "{n} copies in the Trash, {size} freed": "Копий в корзине: {n}, освобождено {size}",
    "Sort by size": "Сортировать по размеру",
    "Size": "Размер",
    "Lost processes · {n}": "Потерянные процессы · {n}",
    "Hyimg servers, Blender and their helpers left running by a test or an agent that ended": "Серверы Hyimg, Blender и их помощники, которые оставил закончившийся тест или агент",
    "Stop": "Остановить",
    "Stop {name}?": "Остановить {name}?",
    "It frees {size}. The app's own servers are not touched": "Освободится {size}. Серверы самого приложения не трогаем",
    // Settings › Diagnostics and Storage: the performance log (ui/perflog.js, review/perflog.py, 2026-10-08)
    "Diagnostics": "Диагностика",
    "Performance log": "Журнал производительности",
    "Nothing is written": "Ничего не записывается",
    "When frames drop, a line with what was on screen goes into the app's cache; its size is under Storage": "Когда кадры проседают, в кэш приложения пишется строка о том, что было на экране. Размер виден в «Хранилище»",
    "Frame drops with what was on screen, written only while the log is on (Settings › Diagnostics)": "Просадки кадров и то, что было на экране. Пишется, только пока журнал включен (Настройки › Диагностика)",
    "Clear the performance log, {size}?": "Очистить журнал производительности, {size}?",
    "Only the log of frame drops in the app's cache": "Только журнал просадок кадров в кэше приложения",
    "Not stopped: {why}": "Не остановлено: {why}",
    "Stopped, {size} freed": "Остановлено, освобождено {size}",
    "Server {port}": "Сервер {port}",
    "Server": "Сервер",
    "{n} h": "{n} ч",
    "{n} min": "{n} мин",
    "Thumbnails per board": "Миниатюры на доску",
    "Thumbnails in all": "Миниатюры всего",
    // ui/setpanel.js: the settings panel of Home and the boards (the language's own names, English and Русский, are never translated)
    "Appearance": "Вид",
    "Performance": "Производительность",
    "Interface": "Интерфейс",
    "Pro": "Pro", "WebKit": "WebKit", "Chromium": "Chromium", "WebGL": "WebGL",
    "App settings": "Настройки приложения",
    "Language": "Язык",
    "Theme": "Тема",
    "Like macOS: light by day, dark in the evening, if the system is set that way": "Как в macOS: днем светлая, вечером темная, если так настроено в системе",
    "Auto": "Авто",
    "Dark theme, graphite paper": "Темная тема, графитовая бумага",
    "Dark": "Темная",
    "Light theme, light paper": "Светлая тема, светлая бумага",
    "theme::Light": "Светлая",
    "Paper grain": "Зерно бумаги",
    "Very fine": "Очень тонкое",
    "grain::Fine": "Тонкое",
    "Visible": "Заметное",
    "grain::Strong": "Сильное",
    "Engine": "Движок",
    "The macOS engine, like Safari: draws on the CPU": "Движок macOS, как Safari: рисует процессором",
    "Chrome's engine inside Hyimg: the GPU draws the board and it stays smooth": "Движок Chrome внутри Hyimg: доска рисуется видеокартой и не тормозит",
    "Rendering": "Отрисовка",
    "Each image as its own element": "Каждая картинка отдельным элементом",
    "Standard": "Обычная",
    "From afar the images are drawn as one canvas (canvas 2D)": "Издалека картинки рисуются одним холстом (canvas 2D)",
    "Canvas": "Холст",
    "From afar the GPU draws the images (WebGL), like Figma": "Издалека картинки рисует видеокарта (WebGL), как в Figma",
    "Notes": "Заметки",
    "Translucent, with a strong blur under them": "Полупрозрачные, под ними сильное размытие",
    "Glass": "Стекло",
    "Solid, no blur": "Плотные, без размытия",
    "Solid": "Плотные",
    "Dots": "Точки",
    "A grid of CSS layers, as always": "Сетка из слоев CSS, как всегда",
    "Classic": "Обычные",
    "One WebGL layer: alive, waves run through them when you drop images": "Одним слоем WebGL: живые, по ним идут волны, когда кладешь картинки",
    "Shadows": "Тени",
    "Panels and buttons float above the board": "Плашки и кнопки парят над доской",
    "With shadows": "С тенями",
    "Panels only": "Только панели",
    "Panels and menus float, the top row and the dock lie flat": "Панели и меню парят, верхний ряд и док лежат плоско",
    "No shadows": "Без теней",
    "Everything lies flat": "Все лежит плоско",
    "Corners": "Углы",
    "Round buttons and panels": "Кнопки и плашки круглые",
    "Round": "Круглые",
    "Stricter: almost square, with a moderate radius": "Строже: почти квадратные, с умеренным радиусом",
    "Paper color": "Цвет бумаги",
    "Paper color in the dark theme": "Цвет бумаги в темной теме",
    "Paper color in the light theme": "Цвет бумаги в светлой теме",
    "Restore the default colors": "Вернуть цвета по умолчанию",
    "Reset": "Сбросить",
    "Dots visibility": "Видимость точек",
    "Dots visibility, percent": "Видимость точек, процентов",
    "For <b>the whole app</b>: Home and every board": "Для <b>всего приложения</b>: главная и все доски",
    // ui/settings-win.js: the settings' window, its rail of sections and its search (owner 2026-10-08)
    "Team & agents": "Команда и агенты", "set::Board": "Доска", "set::Search": "Поиск", "Search settings": "Поиск по настройкам",
    "Profile, folders": "Профиль, папки", "{n} found": "Найдено: {n}", "Nothing found": "Ничего не найдено", "Settings sections": "Разделы настроек",
    "Double-click: the whole window or back": "Двойной клик: на все окно или обратно",
    // the settings at the side of a board or as a window, round 11 (owner 2026-10-08)
    "set::Settings": "Настройки", "Dock to the side": "Прикрепить сбоку", "Open as a window": "Открыть окном", "Close · Esc": "Закрыть · Esc",
    "Fold or unfold": "Свернуть или развернуть", "No profile": "Нет профиля", "Agents: {a} · team: {p}": "Агенты: {a} · команда: {p}",
    "{grain} grain · {dots}% dots": "зерно {grain} · точки {dots}%", "{n} of {m} on": "включено {n} из {m}",
    "{hide} · key hints: {keys}": "{hide} · подсказки клавиш: {keys}",
    "Hide interface · ⌘.": "Скрыть интерфейс · ⌘.", "Zoom": "Приближение", "Slide": "Сдвиг",
    "Everything around the board grows a little and fades out": "Все вокруг доски чуть увеличивается и растворяется",
    "Everything slides off to its edge and fades": "Все уезжает к своему краю и растворяется",
    "Open board links in the app": "Открывать ссылки на доску в приложении", "Off": "Выкл", "On": "Вкл",
    "A board link opened in a browser stays there and offers Hyimg": "Ссылка на доску остается в браузере и предлагает открыть Hyimg",
    "A board link opened in a browser goes straight to Hyimg": "Ссылка на доску из браузера сразу открывает Hyimg",
    "Key hints": "Подсказки клавиш", "Always": "Всегда", "Until learned": "Пока не запомню",
    "Key hints and tips always show, learned ones too": "Подсказки клавиш и советы видны всегда, даже выученные",
    "A key used 5 times and a tip used once are no longer shown": "Клавиша после 5 раз и совет после первого больше не показываются",
    "No key hints, Hint bar or tips": "Без подсказок клавиш, строки подсказок и советов",
    // ui/hy/keyhint.js: the words beside the keys (ui/boardhints.js, the studios); «hint::» keeps them apart from buttons. A surface's
    // hint is the ↵ alone, no word (owner 2026-10-09): the words are the capsule's (a drag, a resize) and the Hint bar's
    "hint::Done": "Готово", "hint::One axis": "По одной оси", "hint::From the centre": "От центра", "hint::Keep proportions": "Сохранить пропорции",
    "hint::45°": "45°", "hint::Square": "Квадрат", "hint::Circle": "Круг", "hint::Add to selection": "Добавить к выделению", "hint::Delete": "Удалить",
    "hint::Proportions": "Пропорции", "hint::Brush size": "Размер кисти", "hint::Black / white": "Черный / белый", "hint::Orbit": "Вращать",
    "hint::Save": "Сохранить", "hint::Back": "Назад", "hint::Select an element": "Выбрать элемент", "hint::Comment": "Комментарий", "hint::Space": "Пробел",
    // ui/hy/tip.js: a tip's place (round 12's version 9, owner 2026-10-09); the tips of the board (ui/boardhints.js) and the library (ui/libtips.js)
    "Hide tips here": "Скрыть советы здесь", "Tips are off here · click the bulb to bring them back": "Советы здесь скрыты · клик по лампочке вернет их",
    "tip::<b>N</b> puts a note here": "<b>N</b> ставит здесь заметку", "tip::<b>⌘V</b> pastes a picture": "<b>⌘V</b> вставляет картинку",
    "tip::<b>Drag a folder</b> from the library: it lands as a block": "<b>Перетащите папку</b> из библиотеки: она ляжет блоком",
    "tip::<b>Drag a folder</b> onto the board: it lands as a block": "<b>Перетащите папку</b> на доску: она ляжет блоком",
    "tip::<b>⌥-click</b> a filter excludes it at once": "<b>⌥-клик</b> по фильтру сразу исключает его",
    "tip::<b>⌃Tab</b> returns to the board you had before": "<b>⌃Tab</b> возвращает на прошлую доску",
    // applink.js: a board opened in a browser offers the app; «Copy as ›» on the board, the app's link and the browser's (owner 2026-10-07)
    "Open in Hyimg": "Открыть в Hyimg",
    "Stay in browser": "Остаться в браузере",
    "App link": "Ссылку для приложения",
    "Browser link": "Ссылку для браузера",
    "App link to this view": "Ссылку на этот вид для приложения",
    "Browser link to this view": "Ссылку на этот вид для браузера",
    "Copy app link to this view": "Копировать ссылку на этот вид для приложения",
    "Copy browser link to this view": "Копировать ссылку на этот вид для браузера",
    "App link copied: it opens Hyimg on this object": "Ссылка для приложения скопирована: откроет Hyimg на этом объекте",
    "App link to this view copied": "Ссылка на этот вид для приложения скопирована",
    "Link copied: it opens and shows this object": "Ссылка скопирована: откроет и покажет этот объект",
    "Link to this view copied": "Ссылка на этот вид скопирована",
    "This board is not in the app's catalog": "Этой доски нет в каталоге приложения",
    "The linked page is not on this board": "Страницы из ссылки на этой доске нет",
    // bellrow.js: when a bell row came, the board's bell and Home's (the same words as ui/i18n.js T.ago)
    "just now": "только что",
    "{n} min ago": "{n} мин назад",
    "{n} h ago": "{n} ч назад",
    // people.js: who made a change, the profile, shared and private boards (owner 2026-10-07)
    "Not saved: {why}": "Не сохранено: {why}",
    "Someone": "Кто-то",
    "Agent": "Агент",
    "edited by": "изменил(а)",
    "What's your name?": "Как вас зовут?",
    "Your name and colour mark <b>your changes</b> on shared boards": "Имя и цвет отмечают <b>ваши правки</b> на общих досках",
    "person::Name": "Имя",
    "Continue": "Продолжить",
    "Profile": "Профиль",
    "No profile on this Mac": "На этом Mac нет профиля",
    "Introduce yourself…": "Представиться…",
    "Shared folder": "Общая папка",
    "Private folder": "Личная папка",
    "not chosen": "не выбрана",
    "Choose…": "Выбрать…",
    "Change…": "Сменить…",
    "Only in the Mac app": "Только в приложении для Mac",
    "People": "Люди",
    "How {name} shows on this Mac": "Как {name} подписан на этом Mac",
    "Sign out of the profile": "Выйти из профиля",
    "“Only for me” is <b>a label, not privacy</b>: on one Dropbox account the files reach both Macs": "«Только для меня» это <b>метка, а не защита</b>: на одном аккаунте Dropbox файлы есть на обоих Mac",
    // dropbox.js: boards in Dropbox not on this Mac, a link's board to add (owner 2026-10-08)
    "Add this board from Dropbox": "Добавить эту доску из Dropbox",
    "dropbox::Add": "Добавить",
    "Not now": "Не сейчас",
    "Boards in Dropbox not on this Mac": "Доски в Dropbox, которых нет на этом Mac",
    "Dropbox syncs these folders to this Mac: <b>Add</b> lists a board here": "Dropbox синхронизирует эти папки на этот Mac: <b>Добавить</b> внесет доску в список",
    "AI": "ИИ",
    "Only for me": "Только для меня",
    "Visibility": "Видимость",
    "vis::All": "Все",
    "vis::Shared": "Общая",
    "filter::Shared": "Общие",
    "Only mine": "Только мои",
    "Choose the shared and the private folder in Settings › Profile first": "Сначала выберите общую и личную папку в Настройках › Профиль",
    // people.js, avatar.js: Team, agents, the picture (owner 2026-10-07)
    "Agents": "Агенты",
    "Team": "Команда",
    "Hidden": "Скрытые",
    "Show": "Показать",
    "Hide {name}": "Скрыть: {name}",
    "Picture": "Фото",
    "Your picture": "Ваше фото",
    "not a picture": "это не картинка",
    "Claude, Codex and the others show here <b>once they act for you</b>": "Claude, Codex и другие появятся здесь, <b>когда начнут работать за вас</b>",
    // people.js, crop.js: a picture placed in a round window, the agents' badges (owner 2026-10-08)
    "not yet": "пока нет",
    "Change the {name} badge": "Сменить значок {name}",
    "The default {name} badge": "Вернуть значок {name}",
    "The {name} badge": "Значок {name}",
    "Drag to place, scroll to zoom": "Перетащите, чтобы выбрать место, колесо меняет масштаб",
    "Save": "Сохранить",
    "The board is already there": "Доска уже там",
    // macnotif.js: Settings › Notifications, the Mac's banners (owner 2026-10-08)
    "set::Notifications": "Уведомления", "Mac notifications": "Уведомления Mac",
    "An agent placed something on a board": "Агент что-то положил на доску", "A comment on a board": "Комментарий на доске",
    "A reply to me": "Ответ мне", "I or my agent was @mentioned": "Упомянули меня или моего агента", "A reply to my note": "Ответ на мою заметку",
    "Only when Hyimg is in the background": "Только когда Hyimg в фоне",
    // plugins.js: Settings › Plugins (owner 2026-10-07)
    "Plugins": "Плагины",
    "No plugins": "Плагинов нет",
    "Add plugin…": "Добавить плагин…",
    "A plugin is a folder with <b>manifest.json</b>. Off, <b>its cards stay</b> on the boards as pictures": "Плагин это папка с <b>manifest.json</b>. Если он выключен, <b>его карточки остаются</b> на досках картинками",
    "Turn {name} on or off": "Включить или выключить {name}",
    "More for {name}": "Еще для {name}",
    "Show in Finder": "Показать в Finder",
    "Copy the path": "Скопировать путь",
    "Path copied": "Путь скопирован",
    "Remove…": "Убрать…",
    "Remove": "Убрать",
    "Remove «{name}»?": "Убрать «{name}»?",
    "Only its link in the plugins folder goes. The plugin's own folder stays where it is": "Уйдет только ссылка в папке плагинов. Папка самого плагина останется на месте",
    "It comes from HYIMG_PLUGINS, not from the plugins folder": "Он подключен через HYIMG_PLUGINS, а не из папки плагинов",
    "A folder, not a link: move it in Finder": "Это папка, а не ссылка: переместите ее в Finder",
    "«{name}» added": "«{name}» добавлен",
    "«{name}» removed": "«{name}» убран",
    "Not added: {why}": "Не добавлен: {why}",
    "Not removed: {why}": "Не убран: {why}",
    "the server did not answer": "сервер не ответил",
    "no manifest.json": "нет manifest.json",
    "manifest.json is broken": "manifest.json не читается",
    // plugins-board.js: on and off on a board, a card whose plugin is off
    "Turns off when you leave {mode}": "Выключится, когда выйдете из {mode}",
    "Turns on when you leave {mode}": "Включится, когда выйдете из {mode}",
    "Turns off when you leave the studio": "Выключится, когда выйдете из студии",
    "Turns on when you leave the studio": "Включится, когда выйдете из студии",
    "Plugin off": "Плагин выключен",
    "No plugin": "Нет плагина",
    "Turn it on in Settings › Plugins: the card stays as it was": "Включите его в Настройках › Плагины, карточка осталась как была",
    "Its plugin is not installed: the card stays as it was": "Его плагин не установлен, карточка осталась как была",
    "{name} is off: turn it on in Settings › Plugins": "{name} выключен: включите его в Настройках › Плагины",
    "The board reloaded for its plugins 3 times in a row: stopped": "Доска 3 раза подряд перезагрузилась из-за плагинов, остановлено",
    // merge.js: a save merged with changes made elsewhere (review/merge.py, 2026-10-08); quietly, a toast only for a clash (2026-10-09)
    "{who} merged {n} changes": ["{who}: слита {n} правка", "{who}: слиты {n} правки", "{who}: слито {n} правок"],
    "You and {who} changed «{what}»: theirs is kept": "Вы и {who} изменили «{what}»: оставлена их правка",
    "You and {who} changed «{what}»: yours is kept": "Вы и {who} изменили «{what}»: оставлена ваша правка",
    "You and {who} both changed {n} things: the newer changes are kept, the others are in History": "Вы и {who} изменили одно и то же ({n}): оставлены поздние правки, другие в Истории",
    "{what}: kept the change by {who}": "{what}: оставлена правка {who}",
    "Changes merged": "Правки слиты",
    "Dropbox copy merged": "Слита копия Dropbox",
    "Position": "Положение",
    "Title": "Название",
    "Members": "Состав",
    "Deleted on one side": "Удалено с одной стороны",
    // switcher.js: ⌃Tab's cards, the crumb's list of boards, a board loading behind the one in front; setpanel.js: the boards' sleep (2026-10-08)
    "Open boards": "Открытые доски", "board::Open": "Открыта", "Warm · {ago}": "Теплая · {ago}", "Asleep · {ago}": "Спит · {ago}",
    "Waking": "Просыпается", "board::Opening": "Открывается", "switch::All boards": "Все доски", "switch::Home": "Главная", "switch::now": "только что",
    "Hold <b>⌃</b>, <b>Tab</b> to the next, release to open": "Держите <b>⌃</b>, <b>Tab</b> к следующей, отпустите, чтобы открыть",
    "Waking “{name}”": "«{name}» просыпается", "Opening “{name}”": "Открываю «{name}»",
    "Sleep background boards": "Усыплять фоновые доски", "5 min": "5 мин", "10 min": "10 мин", "30 min": "30 мин", "Never": "Никогда",
    "A board left for 5 minutes gives its memory back, its server keeps working": "Доска, оставленная на 5 минут, отдает память, ее сервер работает дальше",
    "A board left for 10 minutes gives its memory back, its server keeps working": "Доска, оставленная на 10 минут, отдает память, ее сервер работает дальше",
    "A board left for 30 minutes gives its memory back, its server keeps working": "Доска, оставленная на 30 минут, отдает память, ее сервер работает дальше",
    "Boards left behind keep their pages and memory": "Оставленные доски держат свои страницы и память",
    // homearchive.js: Home's standard Archive (owner 2026-10-08)
    "Archive": "Архив",
    "Archived": "В архиве",
    "In Archive": "В архиве",
    "Move to Archive": "В архив",
    "Restore": "Вернуть",
    "to “{name}”": "в «{name}»",
    "to No project": "в «Без проекта»",
    "Old boards that show nowhere else": "Старые доски, которых больше нигде не видно",
    "Nothing in the Archive": "В архиве пусто",
    "<b>Drag boards here</b> or choose <b>Move to Archive</b> in a board's menu": "<b>Перетащи доски сюда</b> или выбери <b>В архив</b> в меню доски",
  },
});
